<?php

namespace DDEX\DSR\DSR_410;

/**
 * Class representing SalesToSocietyByTerritoryType
 *
 * A ddex:Composite containing details of ddex:SalesTransactions reported by a ddex:DSP to a ddex:MusicalWork ddex:Licensor for a specific ddex:Territory.
 * XSD Type: SalesToSocietyByTerritory
 */
class SalesToSocietyByTerritoryType
{
    /**
     * The ddex:Language and script for the ddex:Elements of the SalesByTerritory as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. ddex:Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML ddex:Attribute.
     *
     * @var string $languageAndScriptCode
     */
    private $languageAndScriptCode = null;

    /**
     * A ddex:Territory for which ddex:SalesTransactions are reported (represented by an ISO 3166-1 iso3166a2:TerritoryCode).
     *
     * @var string[] $territoryCode
     */
    private $territoryCode = [
        
    ];

    /**
     * A ddex:Composite containing details of a ddex:TaxRate applicable to the total ddex:Amount to be paid as value added tax. Within the DSR ddex:Message, only one of the two ddex:TaxRate ddex:Elements (here and in the DetailedDeal ddex:Composite) may be filled.
     *
     * @var \DDEX\ddexC\TaxRateType[] $taxRate
     */
    private $taxRate = [
        
    ];

    /**
     * A ddex:Composite containing details of the ddex:Deal under which sales were transacted. The reported figures are based on best knowledge on the side of the ddex:MessageSender with respect to the intellectual property rights controlled by the ddex:MessageRecipient (the default is that 100% ownership is assumed).
     *
     * @var \DDEX\DSR\DSR_410\DealForSocietiesType $deal
     */
    private $deal = null;

    /**
     * A ddex:Composite containing details of the ddex:SalesTransactions for a ddex:Release, reported by the ddex:DSP to the society.
     *
     * @var \DDEX\DSR\DSR_410\ReleaseTransactionsToSocietyType[] $releaseTransactions
     */
    private $releaseTransactions = [
        
    ];

    /**
     * A ddex:Composite containing a NumberOfSubscribers for the ddex:UseType for the ddex:DSP (applicable only where a ddex:Subscription ddex:Service is employed).
     *
     * @var \DDEX\ddexC\NumberOfSubscribersType $numberOfSubscribers
     */
    private $numberOfSubscribers = null;

    /**
     * A ddex:Composite containing details of the gross ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @var \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspGrossRevenue
     */
    private $dspGrossRevenue = null;

    /**
     * A ddex:Composite containing details of the net ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @var \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspNetRevenue
     */
    private $dspNetRevenue = null;

    /**
     * A ddex:Composite containing details of the ddex:Amount deducted by the ddex:DSP from net ddex:Revenue, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @var \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspDeductionsAmount
     */
    private $dspDeductionsAmount = null;

    /**
     * A ddex:Composite containing details of the percentage which represents a share of a net ddex:Revenue generated by the ddex:DSP which is due to the record company, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @var \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $percentageNetRevenueShare
     */
    private $percentageNetRevenueShare = null;

    /**
     * The minimum ddex:Amount that has to be paid by each ddex:Customer to the ddex:DSP for a ddex:Subscription for the ddex:UseType.
     *
     * @var float $minimumAmountPerCustomer
     */
    private $minimumAmountPerCustomer = null;

    /**
     * A ddex:Composite containing details of a minimum ddex:Amount due to the ddex:WorkLicensor that has to be paid per ddex:Collection.
     *
     * @var \DDEX\ddexC\AmountPerCollectionType[] $minimumAmountPerCollection
     */
    private $minimumAmountPerCollection = [
        
    ];

    /**
     * A ddex:Composite containing details of a maximum ddex:Amount due to the ddex:WorkLicensor that has to be paid per ddex:Collection.
     *
     * @var \DDEX\ddexC\AmountPerCollectionType[] $maximumAmountPerCollection
     */
    private $maximumAmountPerCollection = [
        
    ];

    /**
     * The calculated ddex:Total of ddex:WholesalePricePerUnits (based on 100% of the shares of the ddex:Works or ddex:Releases involved).
     *
     * @var float $totalWholesalePricePerUnit
     */
    private $totalWholesalePricePerUnit = null;

    /**
     * The ddex:TotalWholesalePricePerUnit measured in the ddex:Currency in which they have been accounted (based on 100% of the shares of the ddex:Works or ddex:Releases involved).
     *
     * @var float $totalWholesalePricePerUnitInCurrencyOfAccounting
     */
    private $totalWholesalePricePerUnitInCurrencyOfAccounting = null;

    /**
     * The calculated ddex:Total of ddex:AmountPayables in the ddex:CurrencyOfAccounting (based on 100% of the shares of the ddex:Works or ddex:Releases involved).
     *
     * @var float $totalAmountPayableInCurrencyOfAccounting
     */
    private $totalAmountPayableInCurrencyOfAccounting = null;

    /**
     * The conversion ddex:Rate applicable to the ddex:TotalAmountPayableInCurrencyOfAccounting.
     *
     * @var float $currencyExchangeRate
     */
    private $currencyExchangeRate = null;

    /**
     * A ddex:Composite containing details of a ddex:ConversionRate between the ddex:CurrencyOfAccounting and an alternative ddex:Currency.
     *
     * @var \DDEX\ddexC\ConversionRateType[] $alternativeConversionRate
     */
    private $alternativeConversionRate = [
        
    ];

    /**
     * Gets as languageAndScriptCode
     *
     * The ddex:Language and script for the ddex:Elements of the SalesByTerritory as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. ddex:Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML ddex:Attribute.
     *
     * @return string
     */
    public function getLanguageAndScriptCode()
    {
        return $this->languageAndScriptCode;
    }

    /**
     * Sets a new languageAndScriptCode
     *
     * The ddex:Language and script for the ddex:Elements of the SalesByTerritory as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. ddex:Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML ddex:Attribute.
     *
     * @param string $languageAndScriptCode
     * @return self
     */
    public function setLanguageAndScriptCode($languageAndScriptCode)
    {
        $this->languageAndScriptCode = $languageAndScriptCode;
        return $this;
    }

    /**
     * Adds as territoryCode
     *
     * A ddex:Territory for which ddex:SalesTransactions are reported (represented by an ISO 3166-1 iso3166a2:TerritoryCode).
     *
     * @return self
     * @param string $territoryCode
     */
    public function addToTerritoryCode($territoryCode)
    {
        $this->territoryCode[] = $territoryCode;
        return $this;
    }

    /**
     * isset territoryCode
     *
     * A ddex:Territory for which ddex:SalesTransactions are reported (represented by an ISO 3166-1 iso3166a2:TerritoryCode).
     *
     * @param int|string $index
     * @return bool
     */
    public function issetTerritoryCode($index)
    {
        return isset($this->territoryCode[$index]);
    }

    /**
     * unset territoryCode
     *
     * A ddex:Territory for which ddex:SalesTransactions are reported (represented by an ISO 3166-1 iso3166a2:TerritoryCode).
     *
     * @param int|string $index
     * @return void
     */
    public function unsetTerritoryCode($index)
    {
        unset($this->territoryCode[$index]);
    }

    /**
     * Gets as territoryCode
     *
     * A ddex:Territory for which ddex:SalesTransactions are reported (represented by an ISO 3166-1 iso3166a2:TerritoryCode).
     *
     * @return string[]
     */
    public function getTerritoryCode()
    {
        return $this->territoryCode;
    }

    /**
     * Sets a new territoryCode
     *
     * A ddex:Territory for which ddex:SalesTransactions are reported (represented by an ISO 3166-1 iso3166a2:TerritoryCode).
     *
     * @param string $territoryCode
     * @return self
     */
    public function setTerritoryCode(array $territoryCode)
    {
        $this->territoryCode = $territoryCode;
        return $this;
    }

    /**
     * Adds as taxRate
     *
     * A ddex:Composite containing details of a ddex:TaxRate applicable to the total ddex:Amount to be paid as value added tax. Within the DSR ddex:Message, only one of the two ddex:TaxRate ddex:Elements (here and in the DetailedDeal ddex:Composite) may be filled.
     *
     * @return self
     * @param \DDEX\ddexC\TaxRateType $taxRate
     */
    public function addToTaxRate(\DDEX\ddexC\TaxRateType $taxRate)
    {
        $this->taxRate[] = $taxRate;
        return $this;
    }

    /**
     * isset taxRate
     *
     * A ddex:Composite containing details of a ddex:TaxRate applicable to the total ddex:Amount to be paid as value added tax. Within the DSR ddex:Message, only one of the two ddex:TaxRate ddex:Elements (here and in the DetailedDeal ddex:Composite) may be filled.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetTaxRate($index)
    {
        return isset($this->taxRate[$index]);
    }

    /**
     * unset taxRate
     *
     * A ddex:Composite containing details of a ddex:TaxRate applicable to the total ddex:Amount to be paid as value added tax. Within the DSR ddex:Message, only one of the two ddex:TaxRate ddex:Elements (here and in the DetailedDeal ddex:Composite) may be filled.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetTaxRate($index)
    {
        unset($this->taxRate[$index]);
    }

    /**
     * Gets as taxRate
     *
     * A ddex:Composite containing details of a ddex:TaxRate applicable to the total ddex:Amount to be paid as value added tax. Within the DSR ddex:Message, only one of the two ddex:TaxRate ddex:Elements (here and in the DetailedDeal ddex:Composite) may be filled.
     *
     * @return \DDEX\ddexC\TaxRateType[]
     */
    public function getTaxRate()
    {
        return $this->taxRate;
    }

    /**
     * Sets a new taxRate
     *
     * A ddex:Composite containing details of a ddex:TaxRate applicable to the total ddex:Amount to be paid as value added tax. Within the DSR ddex:Message, only one of the two ddex:TaxRate ddex:Elements (here and in the DetailedDeal ddex:Composite) may be filled.
     *
     * @param \DDEX\ddexC\TaxRateType[] $taxRate
     * @return self
     */
    public function setTaxRate(array $taxRate = null)
    {
        $this->taxRate = $taxRate;
        return $this;
    }

    /**
     * Gets as deal
     *
     * A ddex:Composite containing details of the ddex:Deal under which sales were transacted. The reported figures are based on best knowledge on the side of the ddex:MessageSender with respect to the intellectual property rights controlled by the ddex:MessageRecipient (the default is that 100% ownership is assumed).
     *
     * @return \DDEX\DSR\DSR_410\DealForSocietiesType
     */
    public function getDeal()
    {
        return $this->deal;
    }

    /**
     * Sets a new deal
     *
     * A ddex:Composite containing details of the ddex:Deal under which sales were transacted. The reported figures are based on best knowledge on the side of the ddex:MessageSender with respect to the intellectual property rights controlled by the ddex:MessageRecipient (the default is that 100% ownership is assumed).
     *
     * @param \DDEX\DSR\DSR_410\DealForSocietiesType $deal
     * @return self
     */
    public function setDeal(?\DDEX\DSR\DSR_410\DealForSocietiesType $deal = null)
    {
        $this->deal = $deal;
        return $this;
    }

    /**
     * Adds as releaseTransactions
     *
     * A ddex:Composite containing details of the ddex:SalesTransactions for a ddex:Release, reported by the ddex:DSP to the society.
     *
     * @return self
     * @param \DDEX\DSR\DSR_410\ReleaseTransactionsToSocietyType $releaseTransactions
     */
    public function addToReleaseTransactions(\DDEX\DSR\DSR_410\ReleaseTransactionsToSocietyType $releaseTransactions)
    {
        $this->releaseTransactions[] = $releaseTransactions;
        return $this;
    }

    /**
     * isset releaseTransactions
     *
     * A ddex:Composite containing details of the ddex:SalesTransactions for a ddex:Release, reported by the ddex:DSP to the society.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetReleaseTransactions($index)
    {
        return isset($this->releaseTransactions[$index]);
    }

    /**
     * unset releaseTransactions
     *
     * A ddex:Composite containing details of the ddex:SalesTransactions for a ddex:Release, reported by the ddex:DSP to the society.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetReleaseTransactions($index)
    {
        unset($this->releaseTransactions[$index]);
    }

    /**
     * Gets as releaseTransactions
     *
     * A ddex:Composite containing details of the ddex:SalesTransactions for a ddex:Release, reported by the ddex:DSP to the society.
     *
     * @return \DDEX\DSR\DSR_410\ReleaseTransactionsToSocietyType[]
     */
    public function getReleaseTransactions()
    {
        return $this->releaseTransactions;
    }

    /**
     * Sets a new releaseTransactions
     *
     * A ddex:Composite containing details of the ddex:SalesTransactions for a ddex:Release, reported by the ddex:DSP to the society.
     *
     * @param \DDEX\DSR\DSR_410\ReleaseTransactionsToSocietyType[] $releaseTransactions
     * @return self
     */
    public function setReleaseTransactions(array $releaseTransactions)
    {
        $this->releaseTransactions = $releaseTransactions;
        return $this;
    }

    /**
     * Gets as numberOfSubscribers
     *
     * A ddex:Composite containing a NumberOfSubscribers for the ddex:UseType for the ddex:DSP (applicable only where a ddex:Subscription ddex:Service is employed).
     *
     * @return \DDEX\ddexC\NumberOfSubscribersType
     */
    public function getNumberOfSubscribers()
    {
        return $this->numberOfSubscribers;
    }

    /**
     * Sets a new numberOfSubscribers
     *
     * A ddex:Composite containing a NumberOfSubscribers for the ddex:UseType for the ddex:DSP (applicable only where a ddex:Subscription ddex:Service is employed).
     *
     * @param \DDEX\ddexC\NumberOfSubscribersType $numberOfSubscribers
     * @return self
     */
    public function setNumberOfSubscribers(?\DDEX\ddexC\NumberOfSubscribersType $numberOfSubscribers = null)
    {
        $this->numberOfSubscribers = $numberOfSubscribers;
        return $this;
    }

    /**
     * Gets as dspGrossRevenue
     *
     * A ddex:Composite containing details of the gross ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @return \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType
     */
    public function getDspGrossRevenue()
    {
        return $this->dspGrossRevenue;
    }

    /**
     * Sets a new dspGrossRevenue
     *
     * A ddex:Composite containing details of the gross ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspGrossRevenue
     * @return self
     */
    public function setDspGrossRevenue(?\DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspGrossRevenue = null)
    {
        $this->dspGrossRevenue = $dspGrossRevenue;
        return $this;
    }

    /**
     * Gets as dspNetRevenue
     *
     * A ddex:Composite containing details of the net ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @return \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType
     */
    public function getDspNetRevenue()
    {
        return $this->dspNetRevenue;
    }

    /**
     * Sets a new dspNetRevenue
     *
     * A ddex:Composite containing details of the net ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspNetRevenue
     * @return self
     */
    public function setDspNetRevenue(?\DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspNetRevenue = null)
    {
        $this->dspNetRevenue = $dspNetRevenue;
        return $this;
    }

    /**
     * Gets as dspDeductionsAmount
     *
     * A ddex:Composite containing details of the ddex:Amount deducted by the ddex:DSP from net ddex:Revenue, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @return \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType
     */
    public function getDspDeductionsAmount()
    {
        return $this->dspDeductionsAmount;
    }

    /**
     * Sets a new dspDeductionsAmount
     *
     * A ddex:Composite containing details of the ddex:Amount deducted by the ddex:DSP from net ddex:Revenue, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspDeductionsAmount
     * @return self
     */
    public function setDspDeductionsAmount(?\DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspDeductionsAmount = null)
    {
        $this->dspDeductionsAmount = $dspDeductionsAmount;
        return $this;
    }

    /**
     * Gets as percentageNetRevenueShare
     *
     * A ddex:Composite containing details of the percentage which represents a share of a net ddex:Revenue generated by the ddex:DSP which is due to the record company, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @return \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType
     */
    public function getPercentageNetRevenueShare()
    {
        return $this->percentageNetRevenueShare;
    }

    /**
     * Sets a new percentageNetRevenueShare
     *
     * A ddex:Composite containing details of the percentage which represents a share of a net ddex:Revenue generated by the ddex:DSP which is due to the record company, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $percentageNetRevenueShare
     * @return self
     */
    public function setPercentageNetRevenueShare(?\DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $percentageNetRevenueShare = null)
    {
        $this->percentageNetRevenueShare = $percentageNetRevenueShare;
        return $this;
    }

    /**
     * Gets as minimumAmountPerCustomer
     *
     * The minimum ddex:Amount that has to be paid by each ddex:Customer to the ddex:DSP for a ddex:Subscription for the ddex:UseType.
     *
     * @return float
     */
    public function getMinimumAmountPerCustomer()
    {
        return $this->minimumAmountPerCustomer;
    }

    /**
     * Sets a new minimumAmountPerCustomer
     *
     * The minimum ddex:Amount that has to be paid by each ddex:Customer to the ddex:DSP for a ddex:Subscription for the ddex:UseType.
     *
     * @param float $minimumAmountPerCustomer
     * @return self
     */
    public function setMinimumAmountPerCustomer($minimumAmountPerCustomer)
    {
        $this->minimumAmountPerCustomer = $minimumAmountPerCustomer;
        return $this;
    }

    /**
     * Adds as minimumAmountPerCollection
     *
     * A ddex:Composite containing details of a minimum ddex:Amount due to the ddex:WorkLicensor that has to be paid per ddex:Collection.
     *
     * @return self
     * @param \DDEX\ddexC\AmountPerCollectionType $minimumAmountPerCollection
     */
    public function addToMinimumAmountPerCollection(\DDEX\ddexC\AmountPerCollectionType $minimumAmountPerCollection)
    {
        $this->minimumAmountPerCollection[] = $minimumAmountPerCollection;
        return $this;
    }

    /**
     * isset minimumAmountPerCollection
     *
     * A ddex:Composite containing details of a minimum ddex:Amount due to the ddex:WorkLicensor that has to be paid per ddex:Collection.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetMinimumAmountPerCollection($index)
    {
        return isset($this->minimumAmountPerCollection[$index]);
    }

    /**
     * unset minimumAmountPerCollection
     *
     * A ddex:Composite containing details of a minimum ddex:Amount due to the ddex:WorkLicensor that has to be paid per ddex:Collection.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetMinimumAmountPerCollection($index)
    {
        unset($this->minimumAmountPerCollection[$index]);
    }

    /**
     * Gets as minimumAmountPerCollection
     *
     * A ddex:Composite containing details of a minimum ddex:Amount due to the ddex:WorkLicensor that has to be paid per ddex:Collection.
     *
     * @return \DDEX\ddexC\AmountPerCollectionType[]
     */
    public function getMinimumAmountPerCollection()
    {
        return $this->minimumAmountPerCollection;
    }

    /**
     * Sets a new minimumAmountPerCollection
     *
     * A ddex:Composite containing details of a minimum ddex:Amount due to the ddex:WorkLicensor that has to be paid per ddex:Collection.
     *
     * @param \DDEX\ddexC\AmountPerCollectionType[] $minimumAmountPerCollection
     * @return self
     */
    public function setMinimumAmountPerCollection(array $minimumAmountPerCollection = null)
    {
        $this->minimumAmountPerCollection = $minimumAmountPerCollection;
        return $this;
    }

    /**
     * Adds as maximumAmountPerCollection
     *
     * A ddex:Composite containing details of a maximum ddex:Amount due to the ddex:WorkLicensor that has to be paid per ddex:Collection.
     *
     * @return self
     * @param \DDEX\ddexC\AmountPerCollectionType $maximumAmountPerCollection
     */
    public function addToMaximumAmountPerCollection(\DDEX\ddexC\AmountPerCollectionType $maximumAmountPerCollection)
    {
        $this->maximumAmountPerCollection[] = $maximumAmountPerCollection;
        return $this;
    }

    /**
     * isset maximumAmountPerCollection
     *
     * A ddex:Composite containing details of a maximum ddex:Amount due to the ddex:WorkLicensor that has to be paid per ddex:Collection.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetMaximumAmountPerCollection($index)
    {
        return isset($this->maximumAmountPerCollection[$index]);
    }

    /**
     * unset maximumAmountPerCollection
     *
     * A ddex:Composite containing details of a maximum ddex:Amount due to the ddex:WorkLicensor that has to be paid per ddex:Collection.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetMaximumAmountPerCollection($index)
    {
        unset($this->maximumAmountPerCollection[$index]);
    }

    /**
     * Gets as maximumAmountPerCollection
     *
     * A ddex:Composite containing details of a maximum ddex:Amount due to the ddex:WorkLicensor that has to be paid per ddex:Collection.
     *
     * @return \DDEX\ddexC\AmountPerCollectionType[]
     */
    public function getMaximumAmountPerCollection()
    {
        return $this->maximumAmountPerCollection;
    }

    /**
     * Sets a new maximumAmountPerCollection
     *
     * A ddex:Composite containing details of a maximum ddex:Amount due to the ddex:WorkLicensor that has to be paid per ddex:Collection.
     *
     * @param \DDEX\ddexC\AmountPerCollectionType[] $maximumAmountPerCollection
     * @return self
     */
    public function setMaximumAmountPerCollection(array $maximumAmountPerCollection = null)
    {
        $this->maximumAmountPerCollection = $maximumAmountPerCollection;
        return $this;
    }

    /**
     * Gets as totalWholesalePricePerUnit
     *
     * The calculated ddex:Total of ddex:WholesalePricePerUnits (based on 100% of the shares of the ddex:Works or ddex:Releases involved).
     *
     * @return float
     */
    public function getTotalWholesalePricePerUnit()
    {
        return $this->totalWholesalePricePerUnit;
    }

    /**
     * Sets a new totalWholesalePricePerUnit
     *
     * The calculated ddex:Total of ddex:WholesalePricePerUnits (based on 100% of the shares of the ddex:Works or ddex:Releases involved).
     *
     * @param float $totalWholesalePricePerUnit
     * @return self
     */
    public function setTotalWholesalePricePerUnit($totalWholesalePricePerUnit)
    {
        $this->totalWholesalePricePerUnit = $totalWholesalePricePerUnit;
        return $this;
    }

    /**
     * Gets as totalWholesalePricePerUnitInCurrencyOfAccounting
     *
     * The ddex:TotalWholesalePricePerUnit measured in the ddex:Currency in which they have been accounted (based on 100% of the shares of the ddex:Works or ddex:Releases involved).
     *
     * @return float
     */
    public function getTotalWholesalePricePerUnitInCurrencyOfAccounting()
    {
        return $this->totalWholesalePricePerUnitInCurrencyOfAccounting;
    }

    /**
     * Sets a new totalWholesalePricePerUnitInCurrencyOfAccounting
     *
     * The ddex:TotalWholesalePricePerUnit measured in the ddex:Currency in which they have been accounted (based on 100% of the shares of the ddex:Works or ddex:Releases involved).
     *
     * @param float $totalWholesalePricePerUnitInCurrencyOfAccounting
     * @return self
     */
    public function setTotalWholesalePricePerUnitInCurrencyOfAccounting($totalWholesalePricePerUnitInCurrencyOfAccounting)
    {
        $this->totalWholesalePricePerUnitInCurrencyOfAccounting = $totalWholesalePricePerUnitInCurrencyOfAccounting;
        return $this;
    }

    /**
     * Gets as totalAmountPayableInCurrencyOfAccounting
     *
     * The calculated ddex:Total of ddex:AmountPayables in the ddex:CurrencyOfAccounting (based on 100% of the shares of the ddex:Works or ddex:Releases involved).
     *
     * @return float
     */
    public function getTotalAmountPayableInCurrencyOfAccounting()
    {
        return $this->totalAmountPayableInCurrencyOfAccounting;
    }

    /**
     * Sets a new totalAmountPayableInCurrencyOfAccounting
     *
     * The calculated ddex:Total of ddex:AmountPayables in the ddex:CurrencyOfAccounting (based on 100% of the shares of the ddex:Works or ddex:Releases involved).
     *
     * @param float $totalAmountPayableInCurrencyOfAccounting
     * @return self
     */
    public function setTotalAmountPayableInCurrencyOfAccounting($totalAmountPayableInCurrencyOfAccounting)
    {
        $this->totalAmountPayableInCurrencyOfAccounting = $totalAmountPayableInCurrencyOfAccounting;
        return $this;
    }

    /**
     * Gets as currencyExchangeRate
     *
     * The conversion ddex:Rate applicable to the ddex:TotalAmountPayableInCurrencyOfAccounting.
     *
     * @return float
     */
    public function getCurrencyExchangeRate()
    {
        return $this->currencyExchangeRate;
    }

    /**
     * Sets a new currencyExchangeRate
     *
     * The conversion ddex:Rate applicable to the ddex:TotalAmountPayableInCurrencyOfAccounting.
     *
     * @param float $currencyExchangeRate
     * @return self
     */
    public function setCurrencyExchangeRate($currencyExchangeRate)
    {
        $this->currencyExchangeRate = $currencyExchangeRate;
        return $this;
    }

    /**
     * Adds as alternativeConversionRate
     *
     * A ddex:Composite containing details of a ddex:ConversionRate between the ddex:CurrencyOfAccounting and an alternative ddex:Currency.
     *
     * @return self
     * @param \DDEX\ddexC\ConversionRateType $alternativeConversionRate
     */
    public function addToAlternativeConversionRate(\DDEX\ddexC\ConversionRateType $alternativeConversionRate)
    {
        $this->alternativeConversionRate[] = $alternativeConversionRate;
        return $this;
    }

    /**
     * isset alternativeConversionRate
     *
     * A ddex:Composite containing details of a ddex:ConversionRate between the ddex:CurrencyOfAccounting and an alternative ddex:Currency.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetAlternativeConversionRate($index)
    {
        return isset($this->alternativeConversionRate[$index]);
    }

    /**
     * unset alternativeConversionRate
     *
     * A ddex:Composite containing details of a ddex:ConversionRate between the ddex:CurrencyOfAccounting and an alternative ddex:Currency.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetAlternativeConversionRate($index)
    {
        unset($this->alternativeConversionRate[$index]);
    }

    /**
     * Gets as alternativeConversionRate
     *
     * A ddex:Composite containing details of a ddex:ConversionRate between the ddex:CurrencyOfAccounting and an alternative ddex:Currency.
     *
     * @return \DDEX\ddexC\ConversionRateType[]
     */
    public function getAlternativeConversionRate()
    {
        return $this->alternativeConversionRate;
    }

    /**
     * Sets a new alternativeConversionRate
     *
     * A ddex:Composite containing details of a ddex:ConversionRate between the ddex:CurrencyOfAccounting and an alternative ddex:Currency.
     *
     * @param \DDEX\ddexC\ConversionRateType[] $alternativeConversionRate
     * @return self
     */
    public function setAlternativeConversionRate(array $alternativeConversionRate = null)
    {
        $this->alternativeConversionRate = $alternativeConversionRate;
        return $this;
    }
}

