<?xml version="1.0" encoding="UTF-8"?>
<!-- SCOW Version v0.8.66 210506. -->
<xs:schema xmlns:dpid="http://ddex.net/xml/dpid/20"
           xmlns:avs="http://ddex.net/xml/allowed-value-sets"
           xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://ddex.net/xml/dpid/20"
           elementFormDefault="unqualified"
           attributeFormDefault="unqualified">
   <xs:import namespace="http://ddex.net/xml/allowed-value-sets"
              schemaLocation="http://ddex.net/xml/allowed-value-sets/allowed-value-sets.xsd"/>
   <xs:annotation>
      <xs:documentation>© 2006-2021 Digital Data Exchange, LLC (DDEX)</xs:documentation>
      <xs:documentation>This XML Schema Definition file is, together with all DDEX standards, subject to two licences: If you wish to evaluate whether the standard meets your needs please have a look at the Evaluation Licence at https://kb.ddex.net/display/HBK/Evaluation+Licence+for+DDEX+Standards. If you want to implement and use this DDEX standard, please take out an Implementation Licence. For details please go to http://ddex.net/apply-ddex-implementation-licence.</xs:documentation>
   </xs:annotation>
   <xs:element name="DpidDatabase">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Message in the DDEX Party ID Standard, containing Licensee information.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element name="DpidOwner" maxOccurs="unbounded" type="dpid:DpidOwner">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of an owner of a DDEX Party ID.</xs:documentation>
               </xs:annotation>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:complexType name="Contact">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a Person that can be contacted for specific purposes.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="Name" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The Name of the contact person.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="Email" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An EmailAddress of the contact person.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="Telephone" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A PhoneNumber of the contact person.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="Address" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An Address of the contact person.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="Annotation" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An Annotation of the contact person.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="Role" type="xs:string" use="required">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The role played by the contact person.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="DpidOwner">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of an owner of a DDEX Party ID.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="Status" minOccurs="0" type="avs:DpidStatus">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The Status of the DDEX Party ID.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="DPID">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The DDEX Party ID.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:pattern value="PADPIDA[a-zA-Z0-9]+"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:element name="PreferredDPID" minOccurs="0">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A DDEX Party ID that should be used instead of the current one.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:pattern value="PADPIDA[a-zA-Z0-9]+"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:element name="CompanyName" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The Name of the company owning the DDEX Party ID.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ServiceName" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The Name of the Service associated with the DDEX Party ID.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="LicenseRecord" minOccurs="0" type="avs:LicenseRecord">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The license record of the Party.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="Address" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An Address of the Party.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="Contact"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="dpid:Contact">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a Person that can be contacted for specific purposes.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="SequenceNumber" type="xs:integer" use="required">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The number indicating the order of the owner in a group of owners.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
</xs:schema>
