<?php

namespace DDEX\DSR\DSR_43D1;

/**
 * Class representing SalesToSocietyByTerritoryType
 *
 * A Composite containing details of SalesTransactions reported by a DSP to a MusicalWork Licensor for a specific Territory.
 * XSD Type: SalesToSocietyByTerritory
 */
class SalesToSocietyByTerritoryType
{
    /**
     * The Language and script for the Elements of the SalesByTerritory as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML Attribute.
     *
     * @var string $languageAndScriptCode
     */
    private $languageAndScriptCode = null;

    /**
     * A Territory for which SalesTransactions are reported. The use of ISO TerritoryCodes (or the term 'Worldwide”) is strongly encouraged; TIS TerritoryCodes should only be used if both MessageSender and MessageRecipient are familiar with this standard.
     *
     * @var \DDEX\DSR\DSR_43D1\CurrentTerritoryCodeType[] $territoryCode
     */
    private $territoryCode = [
        
    ];

    /**
     * A Composite containing details of a TaxRate applicable to the total Amount to be paid as value added tax. Within the DSR Message, only one of the two TaxRate Elements (here and in the DetailedDeal Composite) may be filled.
     *
     * @var \DDEX\DSR\DSR_43D1\TaxRateType[] $taxRate
     */
    private $taxRate = [
        
    ];

    /**
     * A Composite containing details of the Deal under which sales were transacted. The reported figures are based on best knowledge on the side of the MessageSender with respect to the intellectual property rights controlled by the MessageRecipient (the default is that 100% ownership is assumed).
     *
     * @var \DDEX\DSR\DSR_43D1\DealForSocietiesType $deal
     */
    private $deal = null;

    /**
     * A Composite containing details of the SalesTransactions for a Release, reported by the DSP to the society.
     *
     * @var \DDEX\DSR\DSR_43D1\ReleaseTransactionsToSocietyType[] $releaseTransactions
     */
    private $releaseTransactions = [
        
    ];

    /**
     * A Composite containing a NumberOfSubscribers for the UseType for the DSP (applicable only where a Subscription Service is employed).
     *
     * @var \DDEX\DSR\DSR_43D1\NumberOfSubscribersType $numberOfSubscribers
     */
    private $numberOfSubscribers = null;

    /**
     * A Composite containing details of the gross Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @var \DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType $dspGrossRevenue
     */
    private $dspGrossRevenue = null;

    /**
     * A Composite containing details of the net Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @var \DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType $dspNetRevenue
     */
    private $dspNetRevenue = null;

    /**
     * A Composite containing details of the Amount deducted by the DSP from net Revenue, specified for a UseType and a DistributionChannelType.
     *
     * @var \DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType $dspDeductionsAmount
     */
    private $dspDeductionsAmount = null;

    /**
     * A Composite containing details of the percentage which represents a share of a net Revenue generated by the DSP which is due to the record company, specified for a UseType and a DistributionChannelType.
     *
     * @var \DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType $percentageNetRevenueShare
     */
    private $percentageNetRevenueShare = null;

    /**
     * The minimum Amount that has to be paid by each Customer to the DSP for a Subscription for the UseType.
     *
     * @var float $minimumAmountPerCustomer
     */
    private $minimumAmountPerCustomer = null;

    /**
     * A Composite containing details of a minimum Amount due to the WorkLicensor that has to be paid per Collection.
     *
     * @var \DDEX\DSR\DSR_43D1\AmountPerCollectionType[] $minimumAmountPerCollection
     */
    private $minimumAmountPerCollection = [
        
    ];

    /**
     * A Composite containing details of a maximum Amount due to the WorkLicensor that has to be paid per Collection.
     *
     * @var \DDEX\DSR\DSR_43D1\AmountPerCollectionType[] $maximumAmountPerCollection
     */
    private $maximumAmountPerCollection = [
        
    ];

    /**
     * The calculated Total of WholesalePricePerUnits (based on 100% of the shares of the Works or Releases involved).
     *
     * @var float $totalWholesalePricePerUnit
     */
    private $totalWholesalePricePerUnit = null;

    /**
     * The TotalWholesalePricePerUnit measured in the Currency in which they have been accounted (based on 100% of the shares of the Works or Releases involved).
     *
     * @var float $totalWholesalePricePerUnitInCurrencyOfAccounting
     */
    private $totalWholesalePricePerUnitInCurrencyOfAccounting = null;

    /**
     * The calculated Total of AmountPayables in the CurrencyOfAccounting (based on 100% of the shares of the Works or Releases involved).
     *
     * @var float $totalAmountPayableInCurrencyOfAccounting
     */
    private $totalAmountPayableInCurrencyOfAccounting = null;

    /**
     * The conversion Rate applicable to the TotalAmountPayableInCurrencyOfAccounting.
     *
     * @var float $currencyExchangeRate
     */
    private $currencyExchangeRate = null;

    /**
     * A Composite containing details of a conversion Rate between the CurrencyOfAccounting and an alternative Currency.
     *
     * @var \DDEX\DSR\DSR_43D1\ConversionRateType[] $alternativeConversionRate
     */
    private $alternativeConversionRate = [
        
    ];

    /**
     * Gets as languageAndScriptCode
     *
     * The Language and script for the Elements of the SalesByTerritory as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML Attribute.
     *
     * @return string
     */
    public function getLanguageAndScriptCode()
    {
        return $this->languageAndScriptCode;
    }

    /**
     * Sets a new languageAndScriptCode
     *
     * The Language and script for the Elements of the SalesByTerritory as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML Attribute.
     *
     * @param string $languageAndScriptCode
     * @return self
     */
    public function setLanguageAndScriptCode($languageAndScriptCode)
    {
        $this->languageAndScriptCode = $languageAndScriptCode;
        return $this;
    }

    /**
     * Adds as territoryCode
     *
     * A Territory for which SalesTransactions are reported. The use of ISO TerritoryCodes (or the term 'Worldwide”) is strongly encouraged; TIS TerritoryCodes should only be used if both MessageSender and MessageRecipient are familiar with this standard.
     *
     * @return self
     * @param \DDEX\DSR\DSR_43D1\CurrentTerritoryCodeType $territoryCode
     */
    public function addToTerritoryCode(\DDEX\DSR\DSR_43D1\CurrentTerritoryCodeType $territoryCode)
    {
        $this->territoryCode[] = $territoryCode;
        return $this;
    }

    /**
     * isset territoryCode
     *
     * A Territory for which SalesTransactions are reported. The use of ISO TerritoryCodes (or the term 'Worldwide”) is strongly encouraged; TIS TerritoryCodes should only be used if both MessageSender and MessageRecipient are familiar with this standard.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetTerritoryCode($index)
    {
        return isset($this->territoryCode[$index]);
    }

    /**
     * unset territoryCode
     *
     * A Territory for which SalesTransactions are reported. The use of ISO TerritoryCodes (or the term 'Worldwide”) is strongly encouraged; TIS TerritoryCodes should only be used if both MessageSender and MessageRecipient are familiar with this standard.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetTerritoryCode($index)
    {
        unset($this->territoryCode[$index]);
    }

    /**
     * Gets as territoryCode
     *
     * A Territory for which SalesTransactions are reported. The use of ISO TerritoryCodes (or the term 'Worldwide”) is strongly encouraged; TIS TerritoryCodes should only be used if both MessageSender and MessageRecipient are familiar with this standard.
     *
     * @return \DDEX\DSR\DSR_43D1\CurrentTerritoryCodeType[]
     */
    public function getTerritoryCode()
    {
        return $this->territoryCode;
    }

    /**
     * Sets a new territoryCode
     *
     * A Territory for which SalesTransactions are reported. The use of ISO TerritoryCodes (or the term 'Worldwide”) is strongly encouraged; TIS TerritoryCodes should only be used if both MessageSender and MessageRecipient are familiar with this standard.
     *
     * @param \DDEX\DSR\DSR_43D1\CurrentTerritoryCodeType[] $territoryCode
     * @return self
     */
    public function setTerritoryCode(array $territoryCode)
    {
        $this->territoryCode = $territoryCode;
        return $this;
    }

    /**
     * Adds as taxRate
     *
     * A Composite containing details of a TaxRate applicable to the total Amount to be paid as value added tax. Within the DSR Message, only one of the two TaxRate Elements (here and in the DetailedDeal Composite) may be filled.
     *
     * @return self
     * @param \DDEX\DSR\DSR_43D1\TaxRateType $taxRate
     */
    public function addToTaxRate(\DDEX\DSR\DSR_43D1\TaxRateType $taxRate)
    {
        $this->taxRate[] = $taxRate;
        return $this;
    }

    /**
     * isset taxRate
     *
     * A Composite containing details of a TaxRate applicable to the total Amount to be paid as value added tax. Within the DSR Message, only one of the two TaxRate Elements (here and in the DetailedDeal Composite) may be filled.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetTaxRate($index)
    {
        return isset($this->taxRate[$index]);
    }

    /**
     * unset taxRate
     *
     * A Composite containing details of a TaxRate applicable to the total Amount to be paid as value added tax. Within the DSR Message, only one of the two TaxRate Elements (here and in the DetailedDeal Composite) may be filled.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetTaxRate($index)
    {
        unset($this->taxRate[$index]);
    }

    /**
     * Gets as taxRate
     *
     * A Composite containing details of a TaxRate applicable to the total Amount to be paid as value added tax. Within the DSR Message, only one of the two TaxRate Elements (here and in the DetailedDeal Composite) may be filled.
     *
     * @return \DDEX\DSR\DSR_43D1\TaxRateType[]
     */
    public function getTaxRate()
    {
        return $this->taxRate;
    }

    /**
     * Sets a new taxRate
     *
     * A Composite containing details of a TaxRate applicable to the total Amount to be paid as value added tax. Within the DSR Message, only one of the two TaxRate Elements (here and in the DetailedDeal Composite) may be filled.
     *
     * @param \DDEX\DSR\DSR_43D1\TaxRateType[] $taxRate
     * @return self
     */
    public function setTaxRate(array $taxRate = null)
    {
        $this->taxRate = $taxRate;
        return $this;
    }

    /**
     * Gets as deal
     *
     * A Composite containing details of the Deal under which sales were transacted. The reported figures are based on best knowledge on the side of the MessageSender with respect to the intellectual property rights controlled by the MessageRecipient (the default is that 100% ownership is assumed).
     *
     * @return \DDEX\DSR\DSR_43D1\DealForSocietiesType
     */
    public function getDeal()
    {
        return $this->deal;
    }

    /**
     * Sets a new deal
     *
     * A Composite containing details of the Deal under which sales were transacted. The reported figures are based on best knowledge on the side of the MessageSender with respect to the intellectual property rights controlled by the MessageRecipient (the default is that 100% ownership is assumed).
     *
     * @param \DDEX\DSR\DSR_43D1\DealForSocietiesType $deal
     * @return self
     */
    public function setDeal(?\DDEX\DSR\DSR_43D1\DealForSocietiesType $deal = null)
    {
        $this->deal = $deal;
        return $this;
    }

    /**
     * Adds as releaseTransactions
     *
     * A Composite containing details of the SalesTransactions for a Release, reported by the DSP to the society.
     *
     * @return self
     * @param \DDEX\DSR\DSR_43D1\ReleaseTransactionsToSocietyType $releaseTransactions
     */
    public function addToReleaseTransactions(\DDEX\DSR\DSR_43D1\ReleaseTransactionsToSocietyType $releaseTransactions)
    {
        $this->releaseTransactions[] = $releaseTransactions;
        return $this;
    }

    /**
     * isset releaseTransactions
     *
     * A Composite containing details of the SalesTransactions for a Release, reported by the DSP to the society.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetReleaseTransactions($index)
    {
        return isset($this->releaseTransactions[$index]);
    }

    /**
     * unset releaseTransactions
     *
     * A Composite containing details of the SalesTransactions for a Release, reported by the DSP to the society.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetReleaseTransactions($index)
    {
        unset($this->releaseTransactions[$index]);
    }

    /**
     * Gets as releaseTransactions
     *
     * A Composite containing details of the SalesTransactions for a Release, reported by the DSP to the society.
     *
     * @return \DDEX\DSR\DSR_43D1\ReleaseTransactionsToSocietyType[]
     */
    public function getReleaseTransactions()
    {
        return $this->releaseTransactions;
    }

    /**
     * Sets a new releaseTransactions
     *
     * A Composite containing details of the SalesTransactions for a Release, reported by the DSP to the society.
     *
     * @param \DDEX\DSR\DSR_43D1\ReleaseTransactionsToSocietyType[] $releaseTransactions
     * @return self
     */
    public function setReleaseTransactions(array $releaseTransactions)
    {
        $this->releaseTransactions = $releaseTransactions;
        return $this;
    }

    /**
     * Gets as numberOfSubscribers
     *
     * A Composite containing a NumberOfSubscribers for the UseType for the DSP (applicable only where a Subscription Service is employed).
     *
     * @return \DDEX\DSR\DSR_43D1\NumberOfSubscribersType
     */
    public function getNumberOfSubscribers()
    {
        return $this->numberOfSubscribers;
    }

    /**
     * Sets a new numberOfSubscribers
     *
     * A Composite containing a NumberOfSubscribers for the UseType for the DSP (applicable only where a Subscription Service is employed).
     *
     * @param \DDEX\DSR\DSR_43D1\NumberOfSubscribersType $numberOfSubscribers
     * @return self
     */
    public function setNumberOfSubscribers(?\DDEX\DSR\DSR_43D1\NumberOfSubscribersType $numberOfSubscribers = null)
    {
        $this->numberOfSubscribers = $numberOfSubscribers;
        return $this;
    }

    /**
     * Gets as dspGrossRevenue
     *
     * A Composite containing details of the gross Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @return \DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType
     */
    public function getDspGrossRevenue()
    {
        return $this->dspGrossRevenue;
    }

    /**
     * Sets a new dspGrossRevenue
     *
     * A Composite containing details of the gross Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @param \DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType $dspGrossRevenue
     * @return self
     */
    public function setDspGrossRevenue(?\DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType $dspGrossRevenue = null)
    {
        $this->dspGrossRevenue = $dspGrossRevenue;
        return $this;
    }

    /**
     * Gets as dspNetRevenue
     *
     * A Composite containing details of the net Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @return \DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType
     */
    public function getDspNetRevenue()
    {
        return $this->dspNetRevenue;
    }

    /**
     * Sets a new dspNetRevenue
     *
     * A Composite containing details of the net Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @param \DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType $dspNetRevenue
     * @return self
     */
    public function setDspNetRevenue(?\DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType $dspNetRevenue = null)
    {
        $this->dspNetRevenue = $dspNetRevenue;
        return $this;
    }

    /**
     * Gets as dspDeductionsAmount
     *
     * A Composite containing details of the Amount deducted by the DSP from net Revenue, specified for a UseType and a DistributionChannelType.
     *
     * @return \DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType
     */
    public function getDspDeductionsAmount()
    {
        return $this->dspDeductionsAmount;
    }

    /**
     * Sets a new dspDeductionsAmount
     *
     * A Composite containing details of the Amount deducted by the DSP from net Revenue, specified for a UseType and a DistributionChannelType.
     *
     * @param \DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType $dspDeductionsAmount
     * @return self
     */
    public function setDspDeductionsAmount(?\DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType $dspDeductionsAmount = null)
    {
        $this->dspDeductionsAmount = $dspDeductionsAmount;
        return $this;
    }

    /**
     * Gets as percentageNetRevenueShare
     *
     * A Composite containing details of the percentage which represents a share of a net Revenue generated by the DSP which is due to the record company, specified for a UseType and a DistributionChannelType.
     *
     * @return \DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType
     */
    public function getPercentageNetRevenueShare()
    {
        return $this->percentageNetRevenueShare;
    }

    /**
     * Sets a new percentageNetRevenueShare
     *
     * A Composite containing details of the percentage which represents a share of a net Revenue generated by the DSP which is due to the record company, specified for a UseType and a DistributionChannelType.
     *
     * @param \DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType $percentageNetRevenueShare
     * @return self
     */
    public function setPercentageNetRevenueShare(?\DDEX\DSR\DSR_43D1\AmountByUseAndDistributionChannelTypeType $percentageNetRevenueShare = null)
    {
        $this->percentageNetRevenueShare = $percentageNetRevenueShare;
        return $this;
    }

    /**
     * Gets as minimumAmountPerCustomer
     *
     * The minimum Amount that has to be paid by each Customer to the DSP for a Subscription for the UseType.
     *
     * @return float
     */
    public function getMinimumAmountPerCustomer()
    {
        return $this->minimumAmountPerCustomer;
    }

    /**
     * Sets a new minimumAmountPerCustomer
     *
     * The minimum Amount that has to be paid by each Customer to the DSP for a Subscription for the UseType.
     *
     * @param float $minimumAmountPerCustomer
     * @return self
     */
    public function setMinimumAmountPerCustomer($minimumAmountPerCustomer)
    {
        $this->minimumAmountPerCustomer = $minimumAmountPerCustomer;
        return $this;
    }

    /**
     * Adds as minimumAmountPerCollection
     *
     * A Composite containing details of a minimum Amount due to the WorkLicensor that has to be paid per Collection.
     *
     * @return self
     * @param \DDEX\DSR\DSR_43D1\AmountPerCollectionType $minimumAmountPerCollection
     */
    public function addToMinimumAmountPerCollection(\DDEX\DSR\DSR_43D1\AmountPerCollectionType $minimumAmountPerCollection)
    {
        $this->minimumAmountPerCollection[] = $minimumAmountPerCollection;
        return $this;
    }

    /**
     * isset minimumAmountPerCollection
     *
     * A Composite containing details of a minimum Amount due to the WorkLicensor that has to be paid per Collection.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetMinimumAmountPerCollection($index)
    {
        return isset($this->minimumAmountPerCollection[$index]);
    }

    /**
     * unset minimumAmountPerCollection
     *
     * A Composite containing details of a minimum Amount due to the WorkLicensor that has to be paid per Collection.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetMinimumAmountPerCollection($index)
    {
        unset($this->minimumAmountPerCollection[$index]);
    }

    /**
     * Gets as minimumAmountPerCollection
     *
     * A Composite containing details of a minimum Amount due to the WorkLicensor that has to be paid per Collection.
     *
     * @return \DDEX\DSR\DSR_43D1\AmountPerCollectionType[]
     */
    public function getMinimumAmountPerCollection()
    {
        return $this->minimumAmountPerCollection;
    }

    /**
     * Sets a new minimumAmountPerCollection
     *
     * A Composite containing details of a minimum Amount due to the WorkLicensor that has to be paid per Collection.
     *
     * @param \DDEX\DSR\DSR_43D1\AmountPerCollectionType[] $minimumAmountPerCollection
     * @return self
     */
    public function setMinimumAmountPerCollection(array $minimumAmountPerCollection = null)
    {
        $this->minimumAmountPerCollection = $minimumAmountPerCollection;
        return $this;
    }

    /**
     * Adds as maximumAmountPerCollection
     *
     * A Composite containing details of a maximum Amount due to the WorkLicensor that has to be paid per Collection.
     *
     * @return self
     * @param \DDEX\DSR\DSR_43D1\AmountPerCollectionType $maximumAmountPerCollection
     */
    public function addToMaximumAmountPerCollection(\DDEX\DSR\DSR_43D1\AmountPerCollectionType $maximumAmountPerCollection)
    {
        $this->maximumAmountPerCollection[] = $maximumAmountPerCollection;
        return $this;
    }

    /**
     * isset maximumAmountPerCollection
     *
     * A Composite containing details of a maximum Amount due to the WorkLicensor that has to be paid per Collection.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetMaximumAmountPerCollection($index)
    {
        return isset($this->maximumAmountPerCollection[$index]);
    }

    /**
     * unset maximumAmountPerCollection
     *
     * A Composite containing details of a maximum Amount due to the WorkLicensor that has to be paid per Collection.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetMaximumAmountPerCollection($index)
    {
        unset($this->maximumAmountPerCollection[$index]);
    }

    /**
     * Gets as maximumAmountPerCollection
     *
     * A Composite containing details of a maximum Amount due to the WorkLicensor that has to be paid per Collection.
     *
     * @return \DDEX\DSR\DSR_43D1\AmountPerCollectionType[]
     */
    public function getMaximumAmountPerCollection()
    {
        return $this->maximumAmountPerCollection;
    }

    /**
     * Sets a new maximumAmountPerCollection
     *
     * A Composite containing details of a maximum Amount due to the WorkLicensor that has to be paid per Collection.
     *
     * @param \DDEX\DSR\DSR_43D1\AmountPerCollectionType[] $maximumAmountPerCollection
     * @return self
     */
    public function setMaximumAmountPerCollection(array $maximumAmountPerCollection = null)
    {
        $this->maximumAmountPerCollection = $maximumAmountPerCollection;
        return $this;
    }

    /**
     * Gets as totalWholesalePricePerUnit
     *
     * The calculated Total of WholesalePricePerUnits (based on 100% of the shares of the Works or Releases involved).
     *
     * @return float
     */
    public function getTotalWholesalePricePerUnit()
    {
        return $this->totalWholesalePricePerUnit;
    }

    /**
     * Sets a new totalWholesalePricePerUnit
     *
     * The calculated Total of WholesalePricePerUnits (based on 100% of the shares of the Works or Releases involved).
     *
     * @param float $totalWholesalePricePerUnit
     * @return self
     */
    public function setTotalWholesalePricePerUnit($totalWholesalePricePerUnit)
    {
        $this->totalWholesalePricePerUnit = $totalWholesalePricePerUnit;
        return $this;
    }

    /**
     * Gets as totalWholesalePricePerUnitInCurrencyOfAccounting
     *
     * The TotalWholesalePricePerUnit measured in the Currency in which they have been accounted (based on 100% of the shares of the Works or Releases involved).
     *
     * @return float
     */
    public function getTotalWholesalePricePerUnitInCurrencyOfAccounting()
    {
        return $this->totalWholesalePricePerUnitInCurrencyOfAccounting;
    }

    /**
     * Sets a new totalWholesalePricePerUnitInCurrencyOfAccounting
     *
     * The TotalWholesalePricePerUnit measured in the Currency in which they have been accounted (based on 100% of the shares of the Works or Releases involved).
     *
     * @param float $totalWholesalePricePerUnitInCurrencyOfAccounting
     * @return self
     */
    public function setTotalWholesalePricePerUnitInCurrencyOfAccounting($totalWholesalePricePerUnitInCurrencyOfAccounting)
    {
        $this->totalWholesalePricePerUnitInCurrencyOfAccounting = $totalWholesalePricePerUnitInCurrencyOfAccounting;
        return $this;
    }

    /**
     * Gets as totalAmountPayableInCurrencyOfAccounting
     *
     * The calculated Total of AmountPayables in the CurrencyOfAccounting (based on 100% of the shares of the Works or Releases involved).
     *
     * @return float
     */
    public function getTotalAmountPayableInCurrencyOfAccounting()
    {
        return $this->totalAmountPayableInCurrencyOfAccounting;
    }

    /**
     * Sets a new totalAmountPayableInCurrencyOfAccounting
     *
     * The calculated Total of AmountPayables in the CurrencyOfAccounting (based on 100% of the shares of the Works or Releases involved).
     *
     * @param float $totalAmountPayableInCurrencyOfAccounting
     * @return self
     */
    public function setTotalAmountPayableInCurrencyOfAccounting($totalAmountPayableInCurrencyOfAccounting)
    {
        $this->totalAmountPayableInCurrencyOfAccounting = $totalAmountPayableInCurrencyOfAccounting;
        return $this;
    }

    /**
     * Gets as currencyExchangeRate
     *
     * The conversion Rate applicable to the TotalAmountPayableInCurrencyOfAccounting.
     *
     * @return float
     */
    public function getCurrencyExchangeRate()
    {
        return $this->currencyExchangeRate;
    }

    /**
     * Sets a new currencyExchangeRate
     *
     * The conversion Rate applicable to the TotalAmountPayableInCurrencyOfAccounting.
     *
     * @param float $currencyExchangeRate
     * @return self
     */
    public function setCurrencyExchangeRate($currencyExchangeRate)
    {
        $this->currencyExchangeRate = $currencyExchangeRate;
        return $this;
    }

    /**
     * Adds as alternativeConversionRate
     *
     * A Composite containing details of a conversion Rate between the CurrencyOfAccounting and an alternative Currency.
     *
     * @return self
     * @param \DDEX\DSR\DSR_43D1\ConversionRateType $alternativeConversionRate
     */
    public function addToAlternativeConversionRate(\DDEX\DSR\DSR_43D1\ConversionRateType $alternativeConversionRate)
    {
        $this->alternativeConversionRate[] = $alternativeConversionRate;
        return $this;
    }

    /**
     * isset alternativeConversionRate
     *
     * A Composite containing details of a conversion Rate between the CurrencyOfAccounting and an alternative Currency.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetAlternativeConversionRate($index)
    {
        return isset($this->alternativeConversionRate[$index]);
    }

    /**
     * unset alternativeConversionRate
     *
     * A Composite containing details of a conversion Rate between the CurrencyOfAccounting and an alternative Currency.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetAlternativeConversionRate($index)
    {
        unset($this->alternativeConversionRate[$index]);
    }

    /**
     * Gets as alternativeConversionRate
     *
     * A Composite containing details of a conversion Rate between the CurrencyOfAccounting and an alternative Currency.
     *
     * @return \DDEX\DSR\DSR_43D1\ConversionRateType[]
     */
    public function getAlternativeConversionRate()
    {
        return $this->alternativeConversionRate;
    }

    /**
     * Sets a new alternativeConversionRate
     *
     * A Composite containing details of a conversion Rate between the CurrencyOfAccounting and an alternative Currency.
     *
     * @param \DDEX\DSR\DSR_43D1\ConversionRateType[] $alternativeConversionRate
     * @return self
     */
    public function setAlternativeConversionRate(array $alternativeConversionRate = null)
    {
        $this->alternativeConversionRate = $alternativeConversionRate;
        return $this;
    }
}

