<?php

namespace DDEX\DSR\DSR_420;

/**
 * Class representing SalesToRecordCompanyByTerritoryType
 *
 * A Composite containing details of SalesTransactions reported by a DSP to a record company for a specific Territory.
 * XSD Type: SalesToRecordCompanyByTerritory
 */
class SalesToRecordCompanyByTerritoryType
{
    /**
     * The Language and script for the Elements of the SalesByTerritory as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML Attribute.
     *
     * @var string $languageAndScriptCode
     */
    private $languageAndScriptCode = null;

    /**
     * A Territory for which SalesTransactions are reported (represented by an ISO 3166-1 TerritoryCode).
     *
     * @var string[] $territoryCode
     */
    private $territoryCode = [
        
    ];

    /**
     * A Composite containing details of a TaxRate applicable to the total Amount to be paid. Within the DSR Message, only one of the two TaxRate Elements (here and in DetailedDeal) may be filled.
     *
     * @var \DDEX\DSR\DSR_420\TaxRateType[] $taxRate
     */
    private $taxRate = [
        
    ];

    /**
     * A Composite containing details of the terms and conditions of the Deal under which sales were transacted. (Note: The Amount reported in this Composite is an estimate based on best knowledge on the side of the MessageSender with respect to the intellectual property rights controlled by the MessageRecipient. The default is that 100% ownership is assumed).
     *
     * @var \DDEX\DSR\DSR_420\DealForRecordCompaniesType $deal
     */
    private $deal = null;

    /**
     * A Composite containing details of the SalesTransactions for a Release, reported by the DSP to the record company.
     *
     * @var \DDEX\DSR\DSR_420\ReleaseTransactionsToRecordCompanyType[] $releaseTransactions
     */
    private $releaseTransactions = [
        
    ];

    /**
     * A Composite containing information to support the calculation of the record company's market share of all Releases provided by a DSP to Consumers for a specified UseType.
     *
     * @var \DDEX\DSR\DSR_420\RecordCompanyMarketShareDataType[] $recordCompanyMarketShareData
     */
    private $recordCompanyMarketShareData = [
        
    ];

    /**
     * A Composite containing a NumberOfSubscribers for the UseType for the DSP (applicable only where a Subscription Service is employed).
     *
     * @var \DDEX\DSR\DSR_420\NumberOfSubscribersType[] $numberOfSubscribers
     */
    private $numberOfSubscribers = [
        
    ];

    /**
     * A Composite containing details of the gross Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @var \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType[] $dspGrossRevenue
     */
    private $dspGrossRevenue = [
        
    ];

    /**
     * A Composite containing details of the net Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @var \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType[] $dspNetRevenue
     */
    private $dspNetRevenue = [
        
    ];

    /**
     * A Composite containing details of the Amount deducted by the DSP from gross Revenue, specified for a UseType and a DistributionChannelType.
     *
     * @var \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType[] $dspDeductionsAmount
     */
    private $dspDeductionsAmount = [
        
    ];

    /**
     * A Composite containing details of the percentage which represents a share of a net Revenue generated by the DSP which is due to the record company, specified for a UseType and a DistributionChannelType.
     *
     * @var \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType[] $percentageNetRevenueShare
     */
    private $percentageNetRevenueShare = [
        
    ];

    /**
     * The minimum Amount that has to be paid by each Customer to the DSP for a Subscription for the UseType.
     *
     * @var float $minimumAmountPerCustomer
     */
    private $minimumAmountPerCustomer = null;

    /**
     * The Amount representing the total wholesale revenue.
     *
     * @var float $wholesaleAmountTotal
     */
    private $wholesaleAmountTotal = null;

    /**
     * The Amount representing the total wholesale revenue reported in the CurrencyOfAccounting.
     *
     * @var float $wholesaleAmountTotalInCurrencyOfAccounting
     */
    private $wholesaleAmountTotalInCurrencyOfAccounting = null;

    /**
     * The calculated Total of AmountPayables in the CurrencyOfAccounting.
     *
     * @var float $totalAmountPayableInCurrencyOfAccounting
     */
    private $totalAmountPayableInCurrencyOfAccounting = null;

    /**
     * The conversion Rate applicable to the TotalAmountPayableInCurrencyOfAccounting.
     *
     * @var float $currencyExchangeRate
     */
    private $currencyExchangeRate = null;

    /**
     * A Composite containing details of a conversion Rate between the CurrencyOfAccounting and an alternative Currency.
     *
     * @var \DDEX\DSR\DSR_420\ConversionRateType[] $alternativeConversionRate
     */
    private $alternativeConversionRate = [
        
    ];

    /**
     * Gets as languageAndScriptCode
     *
     * The Language and script for the Elements of the SalesByTerritory as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML Attribute.
     *
     * @return string
     */
    public function getLanguageAndScriptCode()
    {
        return $this->languageAndScriptCode;
    }

    /**
     * Sets a new languageAndScriptCode
     *
     * The Language and script for the Elements of the SalesByTerritory as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML Attribute.
     *
     * @param string $languageAndScriptCode
     * @return self
     */
    public function setLanguageAndScriptCode($languageAndScriptCode)
    {
        $this->languageAndScriptCode = $languageAndScriptCode;
        return $this;
    }

    /**
     * Adds as territoryCode
     *
     * A Territory for which SalesTransactions are reported (represented by an ISO 3166-1 TerritoryCode).
     *
     * @return self
     * @param string $territoryCode
     */
    public function addToTerritoryCode($territoryCode)
    {
        $this->territoryCode[] = $territoryCode;
        return $this;
    }

    /**
     * isset territoryCode
     *
     * A Territory for which SalesTransactions are reported (represented by an ISO 3166-1 TerritoryCode).
     *
     * @param int|string $index
     * @return bool
     */
    public function issetTerritoryCode($index)
    {
        return isset($this->territoryCode[$index]);
    }

    /**
     * unset territoryCode
     *
     * A Territory for which SalesTransactions are reported (represented by an ISO 3166-1 TerritoryCode).
     *
     * @param int|string $index
     * @return void
     */
    public function unsetTerritoryCode($index)
    {
        unset($this->territoryCode[$index]);
    }

    /**
     * Gets as territoryCode
     *
     * A Territory for which SalesTransactions are reported (represented by an ISO 3166-1 TerritoryCode).
     *
     * @return string[]
     */
    public function getTerritoryCode()
    {
        return $this->territoryCode;
    }

    /**
     * Sets a new territoryCode
     *
     * A Territory for which SalesTransactions are reported (represented by an ISO 3166-1 TerritoryCode).
     *
     * @param string $territoryCode
     * @return self
     */
    public function setTerritoryCode(array $territoryCode)
    {
        $this->territoryCode = $territoryCode;
        return $this;
    }

    /**
     * Adds as taxRate
     *
     * A Composite containing details of a TaxRate applicable to the total Amount to be paid. Within the DSR Message, only one of the two TaxRate Elements (here and in DetailedDeal) may be filled.
     *
     * @return self
     * @param \DDEX\DSR\DSR_420\TaxRateType $taxRate
     */
    public function addToTaxRate(\DDEX\DSR\DSR_420\TaxRateType $taxRate)
    {
        $this->taxRate[] = $taxRate;
        return $this;
    }

    /**
     * isset taxRate
     *
     * A Composite containing details of a TaxRate applicable to the total Amount to be paid. Within the DSR Message, only one of the two TaxRate Elements (here and in DetailedDeal) may be filled.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetTaxRate($index)
    {
        return isset($this->taxRate[$index]);
    }

    /**
     * unset taxRate
     *
     * A Composite containing details of a TaxRate applicable to the total Amount to be paid. Within the DSR Message, only one of the two TaxRate Elements (here and in DetailedDeal) may be filled.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetTaxRate($index)
    {
        unset($this->taxRate[$index]);
    }

    /**
     * Gets as taxRate
     *
     * A Composite containing details of a TaxRate applicable to the total Amount to be paid. Within the DSR Message, only one of the two TaxRate Elements (here and in DetailedDeal) may be filled.
     *
     * @return \DDEX\DSR\DSR_420\TaxRateType[]
     */
    public function getTaxRate()
    {
        return $this->taxRate;
    }

    /**
     * Sets a new taxRate
     *
     * A Composite containing details of a TaxRate applicable to the total Amount to be paid. Within the DSR Message, only one of the two TaxRate Elements (here and in DetailedDeal) may be filled.
     *
     * @param \DDEX\DSR\DSR_420\TaxRateType[] $taxRate
     * @return self
     */
    public function setTaxRate(array $taxRate = null)
    {
        $this->taxRate = $taxRate;
        return $this;
    }

    /**
     * Gets as deal
     *
     * A Composite containing details of the terms and conditions of the Deal under which sales were transacted. (Note: The Amount reported in this Composite is an estimate based on best knowledge on the side of the MessageSender with respect to the intellectual property rights controlled by the MessageRecipient. The default is that 100% ownership is assumed).
     *
     * @return \DDEX\DSR\DSR_420\DealForRecordCompaniesType
     */
    public function getDeal()
    {
        return $this->deal;
    }

    /**
     * Sets a new deal
     *
     * A Composite containing details of the terms and conditions of the Deal under which sales were transacted. (Note: The Amount reported in this Composite is an estimate based on best knowledge on the side of the MessageSender with respect to the intellectual property rights controlled by the MessageRecipient. The default is that 100% ownership is assumed).
     *
     * @param \DDEX\DSR\DSR_420\DealForRecordCompaniesType $deal
     * @return self
     */
    public function setDeal(?\DDEX\DSR\DSR_420\DealForRecordCompaniesType $deal = null)
    {
        $this->deal = $deal;
        return $this;
    }

    /**
     * Adds as releaseTransactions
     *
     * A Composite containing details of the SalesTransactions for a Release, reported by the DSP to the record company.
     *
     * @return self
     * @param \DDEX\DSR\DSR_420\ReleaseTransactionsToRecordCompanyType $releaseTransactions
     */
    public function addToReleaseTransactions(\DDEX\DSR\DSR_420\ReleaseTransactionsToRecordCompanyType $releaseTransactions)
    {
        $this->releaseTransactions[] = $releaseTransactions;
        return $this;
    }

    /**
     * isset releaseTransactions
     *
     * A Composite containing details of the SalesTransactions for a Release, reported by the DSP to the record company.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetReleaseTransactions($index)
    {
        return isset($this->releaseTransactions[$index]);
    }

    /**
     * unset releaseTransactions
     *
     * A Composite containing details of the SalesTransactions for a Release, reported by the DSP to the record company.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetReleaseTransactions($index)
    {
        unset($this->releaseTransactions[$index]);
    }

    /**
     * Gets as releaseTransactions
     *
     * A Composite containing details of the SalesTransactions for a Release, reported by the DSP to the record company.
     *
     * @return \DDEX\DSR\DSR_420\ReleaseTransactionsToRecordCompanyType[]
     */
    public function getReleaseTransactions()
    {
        return $this->releaseTransactions;
    }

    /**
     * Sets a new releaseTransactions
     *
     * A Composite containing details of the SalesTransactions for a Release, reported by the DSP to the record company.
     *
     * @param \DDEX\DSR\DSR_420\ReleaseTransactionsToRecordCompanyType[] $releaseTransactions
     * @return self
     */
    public function setReleaseTransactions(array $releaseTransactions)
    {
        $this->releaseTransactions = $releaseTransactions;
        return $this;
    }

    /**
     * Adds as recordCompanyMarketShareData
     *
     * A Composite containing information to support the calculation of the record company's market share of all Releases provided by a DSP to Consumers for a specified UseType.
     *
     * @return self
     * @param \DDEX\DSR\DSR_420\RecordCompanyMarketShareDataType $recordCompanyMarketShareData
     */
    public function addToRecordCompanyMarketShareData(\DDEX\DSR\DSR_420\RecordCompanyMarketShareDataType $recordCompanyMarketShareData)
    {
        $this->recordCompanyMarketShareData[] = $recordCompanyMarketShareData;
        return $this;
    }

    /**
     * isset recordCompanyMarketShareData
     *
     * A Composite containing information to support the calculation of the record company's market share of all Releases provided by a DSP to Consumers for a specified UseType.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetRecordCompanyMarketShareData($index)
    {
        return isset($this->recordCompanyMarketShareData[$index]);
    }

    /**
     * unset recordCompanyMarketShareData
     *
     * A Composite containing information to support the calculation of the record company's market share of all Releases provided by a DSP to Consumers for a specified UseType.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetRecordCompanyMarketShareData($index)
    {
        unset($this->recordCompanyMarketShareData[$index]);
    }

    /**
     * Gets as recordCompanyMarketShareData
     *
     * A Composite containing information to support the calculation of the record company's market share of all Releases provided by a DSP to Consumers for a specified UseType.
     *
     * @return \DDEX\DSR\DSR_420\RecordCompanyMarketShareDataType[]
     */
    public function getRecordCompanyMarketShareData()
    {
        return $this->recordCompanyMarketShareData;
    }

    /**
     * Sets a new recordCompanyMarketShareData
     *
     * A Composite containing information to support the calculation of the record company's market share of all Releases provided by a DSP to Consumers for a specified UseType.
     *
     * @param \DDEX\DSR\DSR_420\RecordCompanyMarketShareDataType[] $recordCompanyMarketShareData
     * @return self
     */
    public function setRecordCompanyMarketShareData(array $recordCompanyMarketShareData = null)
    {
        $this->recordCompanyMarketShareData = $recordCompanyMarketShareData;
        return $this;
    }

    /**
     * Adds as numberOfSubscribers
     *
     * A Composite containing a NumberOfSubscribers for the UseType for the DSP (applicable only where a Subscription Service is employed).
     *
     * @return self
     * @param \DDEX\DSR\DSR_420\NumberOfSubscribersType $numberOfSubscribers
     */
    public function addToNumberOfSubscribers(\DDEX\DSR\DSR_420\NumberOfSubscribersType $numberOfSubscribers)
    {
        $this->numberOfSubscribers[] = $numberOfSubscribers;
        return $this;
    }

    /**
     * isset numberOfSubscribers
     *
     * A Composite containing a NumberOfSubscribers for the UseType for the DSP (applicable only where a Subscription Service is employed).
     *
     * @param int|string $index
     * @return bool
     */
    public function issetNumberOfSubscribers($index)
    {
        return isset($this->numberOfSubscribers[$index]);
    }

    /**
     * unset numberOfSubscribers
     *
     * A Composite containing a NumberOfSubscribers for the UseType for the DSP (applicable only where a Subscription Service is employed).
     *
     * @param int|string $index
     * @return void
     */
    public function unsetNumberOfSubscribers($index)
    {
        unset($this->numberOfSubscribers[$index]);
    }

    /**
     * Gets as numberOfSubscribers
     *
     * A Composite containing a NumberOfSubscribers for the UseType for the DSP (applicable only where a Subscription Service is employed).
     *
     * @return \DDEX\DSR\DSR_420\NumberOfSubscribersType[]
     */
    public function getNumberOfSubscribers()
    {
        return $this->numberOfSubscribers;
    }

    /**
     * Sets a new numberOfSubscribers
     *
     * A Composite containing a NumberOfSubscribers for the UseType for the DSP (applicable only where a Subscription Service is employed).
     *
     * @param \DDEX\DSR\DSR_420\NumberOfSubscribersType[] $numberOfSubscribers
     * @return self
     */
    public function setNumberOfSubscribers(array $numberOfSubscribers = null)
    {
        $this->numberOfSubscribers = $numberOfSubscribers;
        return $this;
    }

    /**
     * Adds as dspGrossRevenue
     *
     * A Composite containing details of the gross Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @return self
     * @param \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType $dspGrossRevenue
     */
    public function addToDspGrossRevenue(\DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType $dspGrossRevenue)
    {
        $this->dspGrossRevenue[] = $dspGrossRevenue;
        return $this;
    }

    /**
     * isset dspGrossRevenue
     *
     * A Composite containing details of the gross Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetDspGrossRevenue($index)
    {
        return isset($this->dspGrossRevenue[$index]);
    }

    /**
     * unset dspGrossRevenue
     *
     * A Composite containing details of the gross Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetDspGrossRevenue($index)
    {
        unset($this->dspGrossRevenue[$index]);
    }

    /**
     * Gets as dspGrossRevenue
     *
     * A Composite containing details of the gross Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @return \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType[]
     */
    public function getDspGrossRevenue()
    {
        return $this->dspGrossRevenue;
    }

    /**
     * Sets a new dspGrossRevenue
     *
     * A Composite containing details of the gross Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @param \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType[] $dspGrossRevenue
     * @return self
     */
    public function setDspGrossRevenue(array $dspGrossRevenue = null)
    {
        $this->dspGrossRevenue = $dspGrossRevenue;
        return $this;
    }

    /**
     * Adds as dspNetRevenue
     *
     * A Composite containing details of the net Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @return self
     * @param \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType $dspNetRevenue
     */
    public function addToDspNetRevenue(\DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType $dspNetRevenue)
    {
        $this->dspNetRevenue[] = $dspNetRevenue;
        return $this;
    }

    /**
     * isset dspNetRevenue
     *
     * A Composite containing details of the net Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetDspNetRevenue($index)
    {
        return isset($this->dspNetRevenue[$index]);
    }

    /**
     * unset dspNetRevenue
     *
     * A Composite containing details of the net Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetDspNetRevenue($index)
    {
        unset($this->dspNetRevenue[$index]);
    }

    /**
     * Gets as dspNetRevenue
     *
     * A Composite containing details of the net Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @return \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType[]
     */
    public function getDspNetRevenue()
    {
        return $this->dspNetRevenue;
    }

    /**
     * Sets a new dspNetRevenue
     *
     * A Composite containing details of the net Revenue of the DSP for the Territory, specified for a UseType and a DistributionChannelType.
     *
     * @param \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType[] $dspNetRevenue
     * @return self
     */
    public function setDspNetRevenue(array $dspNetRevenue = null)
    {
        $this->dspNetRevenue = $dspNetRevenue;
        return $this;
    }

    /**
     * Adds as dspDeductionsAmount
     *
     * A Composite containing details of the Amount deducted by the DSP from gross Revenue, specified for a UseType and a DistributionChannelType.
     *
     * @return self
     * @param \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType $dspDeductionsAmount
     */
    public function addToDspDeductionsAmount(\DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType $dspDeductionsAmount)
    {
        $this->dspDeductionsAmount[] = $dspDeductionsAmount;
        return $this;
    }

    /**
     * isset dspDeductionsAmount
     *
     * A Composite containing details of the Amount deducted by the DSP from gross Revenue, specified for a UseType and a DistributionChannelType.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetDspDeductionsAmount($index)
    {
        return isset($this->dspDeductionsAmount[$index]);
    }

    /**
     * unset dspDeductionsAmount
     *
     * A Composite containing details of the Amount deducted by the DSP from gross Revenue, specified for a UseType and a DistributionChannelType.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetDspDeductionsAmount($index)
    {
        unset($this->dspDeductionsAmount[$index]);
    }

    /**
     * Gets as dspDeductionsAmount
     *
     * A Composite containing details of the Amount deducted by the DSP from gross Revenue, specified for a UseType and a DistributionChannelType.
     *
     * @return \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType[]
     */
    public function getDspDeductionsAmount()
    {
        return $this->dspDeductionsAmount;
    }

    /**
     * Sets a new dspDeductionsAmount
     *
     * A Composite containing details of the Amount deducted by the DSP from gross Revenue, specified for a UseType and a DistributionChannelType.
     *
     * @param \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType[] $dspDeductionsAmount
     * @return self
     */
    public function setDspDeductionsAmount(array $dspDeductionsAmount = null)
    {
        $this->dspDeductionsAmount = $dspDeductionsAmount;
        return $this;
    }

    /**
     * Adds as percentageNetRevenueShare
     *
     * A Composite containing details of the percentage which represents a share of a net Revenue generated by the DSP which is due to the record company, specified for a UseType and a DistributionChannelType.
     *
     * @return self
     * @param \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType $percentageNetRevenueShare
     */
    public function addToPercentageNetRevenueShare(\DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType $percentageNetRevenueShare)
    {
        $this->percentageNetRevenueShare[] = $percentageNetRevenueShare;
        return $this;
    }

    /**
     * isset percentageNetRevenueShare
     *
     * A Composite containing details of the percentage which represents a share of a net Revenue generated by the DSP which is due to the record company, specified for a UseType and a DistributionChannelType.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetPercentageNetRevenueShare($index)
    {
        return isset($this->percentageNetRevenueShare[$index]);
    }

    /**
     * unset percentageNetRevenueShare
     *
     * A Composite containing details of the percentage which represents a share of a net Revenue generated by the DSP which is due to the record company, specified for a UseType and a DistributionChannelType.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetPercentageNetRevenueShare($index)
    {
        unset($this->percentageNetRevenueShare[$index]);
    }

    /**
     * Gets as percentageNetRevenueShare
     *
     * A Composite containing details of the percentage which represents a share of a net Revenue generated by the DSP which is due to the record company, specified for a UseType and a DistributionChannelType.
     *
     * @return \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType[]
     */
    public function getPercentageNetRevenueShare()
    {
        return $this->percentageNetRevenueShare;
    }

    /**
     * Sets a new percentageNetRevenueShare
     *
     * A Composite containing details of the percentage which represents a share of a net Revenue generated by the DSP which is due to the record company, specified for a UseType and a DistributionChannelType.
     *
     * @param \DDEX\DSR\DSR_420\AmountByUseAndDistributionChannelTypeType[] $percentageNetRevenueShare
     * @return self
     */
    public function setPercentageNetRevenueShare(array $percentageNetRevenueShare = null)
    {
        $this->percentageNetRevenueShare = $percentageNetRevenueShare;
        return $this;
    }

    /**
     * Gets as minimumAmountPerCustomer
     *
     * The minimum Amount that has to be paid by each Customer to the DSP for a Subscription for the UseType.
     *
     * @return float
     */
    public function getMinimumAmountPerCustomer()
    {
        return $this->minimumAmountPerCustomer;
    }

    /**
     * Sets a new minimumAmountPerCustomer
     *
     * The minimum Amount that has to be paid by each Customer to the DSP for a Subscription for the UseType.
     *
     * @param float $minimumAmountPerCustomer
     * @return self
     */
    public function setMinimumAmountPerCustomer($minimumAmountPerCustomer)
    {
        $this->minimumAmountPerCustomer = $minimumAmountPerCustomer;
        return $this;
    }

    /**
     * Gets as wholesaleAmountTotal
     *
     * The Amount representing the total wholesale revenue.
     *
     * @return float
     */
    public function getWholesaleAmountTotal()
    {
        return $this->wholesaleAmountTotal;
    }

    /**
     * Sets a new wholesaleAmountTotal
     *
     * The Amount representing the total wholesale revenue.
     *
     * @param float $wholesaleAmountTotal
     * @return self
     */
    public function setWholesaleAmountTotal($wholesaleAmountTotal)
    {
        $this->wholesaleAmountTotal = $wholesaleAmountTotal;
        return $this;
    }

    /**
     * Gets as wholesaleAmountTotalInCurrencyOfAccounting
     *
     * The Amount representing the total wholesale revenue reported in the CurrencyOfAccounting.
     *
     * @return float
     */
    public function getWholesaleAmountTotalInCurrencyOfAccounting()
    {
        return $this->wholesaleAmountTotalInCurrencyOfAccounting;
    }

    /**
     * Sets a new wholesaleAmountTotalInCurrencyOfAccounting
     *
     * The Amount representing the total wholesale revenue reported in the CurrencyOfAccounting.
     *
     * @param float $wholesaleAmountTotalInCurrencyOfAccounting
     * @return self
     */
    public function setWholesaleAmountTotalInCurrencyOfAccounting($wholesaleAmountTotalInCurrencyOfAccounting)
    {
        $this->wholesaleAmountTotalInCurrencyOfAccounting = $wholesaleAmountTotalInCurrencyOfAccounting;
        return $this;
    }

    /**
     * Gets as totalAmountPayableInCurrencyOfAccounting
     *
     * The calculated Total of AmountPayables in the CurrencyOfAccounting.
     *
     * @return float
     */
    public function getTotalAmountPayableInCurrencyOfAccounting()
    {
        return $this->totalAmountPayableInCurrencyOfAccounting;
    }

    /**
     * Sets a new totalAmountPayableInCurrencyOfAccounting
     *
     * The calculated Total of AmountPayables in the CurrencyOfAccounting.
     *
     * @param float $totalAmountPayableInCurrencyOfAccounting
     * @return self
     */
    public function setTotalAmountPayableInCurrencyOfAccounting($totalAmountPayableInCurrencyOfAccounting)
    {
        $this->totalAmountPayableInCurrencyOfAccounting = $totalAmountPayableInCurrencyOfAccounting;
        return $this;
    }

    /**
     * Gets as currencyExchangeRate
     *
     * The conversion Rate applicable to the TotalAmountPayableInCurrencyOfAccounting.
     *
     * @return float
     */
    public function getCurrencyExchangeRate()
    {
        return $this->currencyExchangeRate;
    }

    /**
     * Sets a new currencyExchangeRate
     *
     * The conversion Rate applicable to the TotalAmountPayableInCurrencyOfAccounting.
     *
     * @param float $currencyExchangeRate
     * @return self
     */
    public function setCurrencyExchangeRate($currencyExchangeRate)
    {
        $this->currencyExchangeRate = $currencyExchangeRate;
        return $this;
    }

    /**
     * Adds as alternativeConversionRate
     *
     * A Composite containing details of a conversion Rate between the CurrencyOfAccounting and an alternative Currency.
     *
     * @return self
     * @param \DDEX\DSR\DSR_420\ConversionRateType $alternativeConversionRate
     */
    public function addToAlternativeConversionRate(\DDEX\DSR\DSR_420\ConversionRateType $alternativeConversionRate)
    {
        $this->alternativeConversionRate[] = $alternativeConversionRate;
        return $this;
    }

    /**
     * isset alternativeConversionRate
     *
     * A Composite containing details of a conversion Rate between the CurrencyOfAccounting and an alternative Currency.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetAlternativeConversionRate($index)
    {
        return isset($this->alternativeConversionRate[$index]);
    }

    /**
     * unset alternativeConversionRate
     *
     * A Composite containing details of a conversion Rate between the CurrencyOfAccounting and an alternative Currency.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetAlternativeConversionRate($index)
    {
        unset($this->alternativeConversionRate[$index]);
    }

    /**
     * Gets as alternativeConversionRate
     *
     * A Composite containing details of a conversion Rate between the CurrencyOfAccounting and an alternative Currency.
     *
     * @return \DDEX\DSR\DSR_420\ConversionRateType[]
     */
    public function getAlternativeConversionRate()
    {
        return $this->alternativeConversionRate;
    }

    /**
     * Sets a new alternativeConversionRate
     *
     * A Composite containing details of a conversion Rate between the CurrencyOfAccounting and an alternative Currency.
     *
     * @param \DDEX\DSR\DSR_420\ConversionRateType[] $alternativeConversionRate
     * @return self
     */
    public function setAlternativeConversionRate(array $alternativeConversionRate = null)
    {
        $this->alternativeConversionRate = $alternativeConversionRate;
        return $this;
    }
}

