<?php

namespace DDEX\DSR\DSR_420;

/**
 * Class representing SoundRecordingType
 *
 * A Composite containing details of a SoundRecording.
 * XSD Type: SoundRecording
 */
class SoundRecordingType
{
    /**
     * The Language and script for the Elements of the SoundRecording as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML Attribute.
     *
     * @var string $languageAndScriptCode
     */
    private $languageAndScriptCode = null;

    /**
     * A Composite containing details of the Type of the SoundRecording.
     *
     * @var \DDEX\DSR\DSR_420\SoundRecordingTypeType $soundRecordingType
     */
    private $soundRecordingType = null;

    /**
     * The Flag indicating whether the SoundRecording is related to an Artist (=True) or not (=False).
     *
     * @var bool $isArtistRelated
     */
    private $isArtistRelated = null;

    /**
     * A Composite containing details of SoundRecordingIds.
     *
     * @var \DDEX\DSR\DSR_420\SoundRecordingIdType[] $soundRecordingId
     */
    private $soundRecordingId = [
        
    ];

    /**
     * A Composite containing details of a MusicalWorkId of a MusicalWork used in the SoundRecording.
     *
     * @var \DDEX\DSR\DSR_420\MusicalWorkIdType[] $indirectSoundRecordingId
     */
    private $indirectSoundRecordingId = [
        
    ];

    /**
     * The Identifier (specific to the Message) of the SoundRecording within the Release which contains it. This is a LocalResourceAnchor starting with the letter A.
     *
     * @var string $resourceReference
     */
    private $resourceReference = null;

    /**
     * A Composite containing details of the ReferenceTitle of the SoundRecording.
     *
     * @var \DDEX\DSR\DSR_420\ReferenceTitleType $referenceTitle
     */
    private $referenceTitle = null;

    /**
     * A Composite containing a Description of the Type of instrumentation of the MusicalWork(s) in the SoundRecording.
     *
     * @var \DDEX\DSR\DSR_420\DescriptionType $instrumentationDescription
     */
    private $instrumentationDescription = null;

    /**
     * The Flag indicating whether the SoundRecording is a Medley (=True) or not (=False).
     *
     * @var bool $isMedley
     */
    private $isMedley = null;

    /**
     * The Flag indicating whether the SoundRecording is a Potpourri (=True) or not (=False).
     *
     * @var bool $isPotpourri
     */
    private $isPotpourri = null;

    /**
     * The Flag indicating whether the SoundRecording is instrumental (=True) or not (=False).
     *
     * @var bool $isInstrumental
     */
    private $isInstrumental = null;

    /**
     * The Flag indicating whether the SoundRecording is used as background to other audio or audiovisual material (=True) or not (=False).
     *
     * @var bool $isBackground
     */
    private $isBackground = null;

    /**
     * The Flag indicating whether the SoundRecording is hidden in some way from the Consumer (=True) or not (=False).
     *
     * @var bool $isHiddenResource
     */
    private $isHiddenResource = null;

    /**
     * The Flag indicating whether the SoundRecording is additional to those on the original Release of which this is a Version (=True) or not (=False).
     *
     * @var bool $isBonusResource
     */
    private $isBonusResource = null;

    /**
     * The Flag indicating whether the SoundRecording is generated by a computer (=True) or not (=False).
     *
     * @var bool $isComputerGenerated
     */
    private $isComputerGenerated = null;

    /**
     * A Flag indicating whether performer information is required (=True) or not (=False) when communicating details of the SoundRecording.
     *
     * @var bool $performerInformationRequired
     */
    private $performerInformationRequired = null;

    /**
     * The Language of the Performance recorded in the SoundRecording (represented by an ISO 639-2 LanguageCode).
     *
     * @var string $languageOfPerformance
     */
    private $languageOfPerformance = null;

    /**
     * The Duration of the SoundRecording (using the ISO 8601:2004 PT[[hhH]mmM]ssS format, where lower case characters indicate variables, upper case characters are part of the xs:string, e.g. one hour, two minutes and three seconds would be PT1H2M3S).
     *
     * @var \DateInterval $duration
     */
    private $duration = null;

    /**
     * A Composite containing details of Identifiers of a License, Claim, RightShare or contract for the MusicalWork(s) used in the SoundRecording.
     *
     * @var \DDEX\DSR\DSR_420\RightsAgreementIdType $rightsAgreementId
     */
    private $rightsAgreementId = null;

    /**
     * A Composite containing details of one or more MusicalWorks contained in the SoundRecording.
     *
     * @var \DDEX\DSR\DSR_420\ResourceMusicalWorkReferenceType[] $resourceMusicalWorkReferenceList
     */
    private $resourceMusicalWorkReferenceList = null;

    /**
     * A Composite containing details of ResourceContainedResourceReferences referring to a Resource that is contained in the current SoundRecording.
     *
     * @var \DDEX\DSR\DSR_420\ResourceContainedResourceReferenceType[] $resourceContainedResourceReferenceList
     */
    private $resourceContainedResourceReferenceList = null;

    /**
     * A Composite containing details of the Date and Place of the Event in which the SoundRecording was created.
     *
     * @var \DDEX\DSR\DSR_420\EventDateType $creationDate
     */
    private $creationDate = null;

    /**
     * A Composite containing details of the Date and Place of the Event in which the SoundRecording was originally mastered (either in analogue or digital form).
     *
     * @var \DDEX\DSR\DSR_420\EventDateType $masteredDate
     */
    private $masteredDate = null;

    /**
     * A Composite containing details of Descriptors and other attributes of the SoundRecording which may vary according to Territory of release.
     *
     * @var \DDEX\DSR\DSR_420\SoundRecordingDetailsByTerritoryType[] $soundRecordingDetailsByTerritory
     */
    private $soundRecordingDetailsByTerritory = [
        
    ];

    /**
     * A URL from which the SoundRecording was sold.
     *
     * @var string $uRL
     */
    private $uRL = null;

    /**
     * Gets as languageAndScriptCode
     *
     * The Language and script for the Elements of the SoundRecording as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML Attribute.
     *
     * @return string
     */
    public function getLanguageAndScriptCode()
    {
        return $this->languageAndScriptCode;
    }

    /**
     * Sets a new languageAndScriptCode
     *
     * The Language and script for the Elements of the SoundRecording as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML Attribute.
     *
     * @param string $languageAndScriptCode
     * @return self
     */
    public function setLanguageAndScriptCode($languageAndScriptCode)
    {
        $this->languageAndScriptCode = $languageAndScriptCode;
        return $this;
    }

    /**
     * Gets as soundRecordingType
     *
     * A Composite containing details of the Type of the SoundRecording.
     *
     * @return \DDEX\DSR\DSR_420\SoundRecordingTypeType
     */
    public function getSoundRecordingType()
    {
        return $this->soundRecordingType;
    }

    /**
     * Sets a new soundRecordingType
     *
     * A Composite containing details of the Type of the SoundRecording.
     *
     * @param \DDEX\DSR\DSR_420\SoundRecordingTypeType $soundRecordingType
     * @return self
     */
    public function setSoundRecordingType(?\DDEX\DSR\DSR_420\SoundRecordingTypeType $soundRecordingType = null)
    {
        $this->soundRecordingType = $soundRecordingType;
        return $this;
    }

    /**
     * Gets as isArtistRelated
     *
     * The Flag indicating whether the SoundRecording is related to an Artist (=True) or not (=False).
     *
     * @return bool
     */
    public function getIsArtistRelated()
    {
        return $this->isArtistRelated;
    }

    /**
     * Sets a new isArtistRelated
     *
     * The Flag indicating whether the SoundRecording is related to an Artist (=True) or not (=False).
     *
     * @param bool $isArtistRelated
     * @return self
     */
    public function setIsArtistRelated($isArtistRelated)
    {
        $this->isArtistRelated = $isArtistRelated;
        return $this;
    }

    /**
     * Adds as soundRecordingId
     *
     * A Composite containing details of SoundRecordingIds.
     *
     * @return self
     * @param \DDEX\DSR\DSR_420\SoundRecordingIdType $soundRecordingId
     */
    public function addToSoundRecordingId(\DDEX\DSR\DSR_420\SoundRecordingIdType $soundRecordingId)
    {
        $this->soundRecordingId[] = $soundRecordingId;
        return $this;
    }

    /**
     * isset soundRecordingId
     *
     * A Composite containing details of SoundRecordingIds.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetSoundRecordingId($index)
    {
        return isset($this->soundRecordingId[$index]);
    }

    /**
     * unset soundRecordingId
     *
     * A Composite containing details of SoundRecordingIds.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetSoundRecordingId($index)
    {
        unset($this->soundRecordingId[$index]);
    }

    /**
     * Gets as soundRecordingId
     *
     * A Composite containing details of SoundRecordingIds.
     *
     * @return \DDEX\DSR\DSR_420\SoundRecordingIdType[]
     */
    public function getSoundRecordingId()
    {
        return $this->soundRecordingId;
    }

    /**
     * Sets a new soundRecordingId
     *
     * A Composite containing details of SoundRecordingIds.
     *
     * @param \DDEX\DSR\DSR_420\SoundRecordingIdType[] $soundRecordingId
     * @return self
     */
    public function setSoundRecordingId(array $soundRecordingId)
    {
        $this->soundRecordingId = $soundRecordingId;
        return $this;
    }

    /**
     * Adds as indirectSoundRecordingId
     *
     * A Composite containing details of a MusicalWorkId of a MusicalWork used in the SoundRecording.
     *
     * @return self
     * @param \DDEX\DSR\DSR_420\MusicalWorkIdType $indirectSoundRecordingId
     */
    public function addToIndirectSoundRecordingId(\DDEX\DSR\DSR_420\MusicalWorkIdType $indirectSoundRecordingId)
    {
        $this->indirectSoundRecordingId[] = $indirectSoundRecordingId;
        return $this;
    }

    /**
     * isset indirectSoundRecordingId
     *
     * A Composite containing details of a MusicalWorkId of a MusicalWork used in the SoundRecording.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetIndirectSoundRecordingId($index)
    {
        return isset($this->indirectSoundRecordingId[$index]);
    }

    /**
     * unset indirectSoundRecordingId
     *
     * A Composite containing details of a MusicalWorkId of a MusicalWork used in the SoundRecording.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetIndirectSoundRecordingId($index)
    {
        unset($this->indirectSoundRecordingId[$index]);
    }

    /**
     * Gets as indirectSoundRecordingId
     *
     * A Composite containing details of a MusicalWorkId of a MusicalWork used in the SoundRecording.
     *
     * @return \DDEX\DSR\DSR_420\MusicalWorkIdType[]
     */
    public function getIndirectSoundRecordingId()
    {
        return $this->indirectSoundRecordingId;
    }

    /**
     * Sets a new indirectSoundRecordingId
     *
     * A Composite containing details of a MusicalWorkId of a MusicalWork used in the SoundRecording.
     *
     * @param \DDEX\DSR\DSR_420\MusicalWorkIdType[] $indirectSoundRecordingId
     * @return self
     */
    public function setIndirectSoundRecordingId(array $indirectSoundRecordingId = null)
    {
        $this->indirectSoundRecordingId = $indirectSoundRecordingId;
        return $this;
    }

    /**
     * Gets as resourceReference
     *
     * The Identifier (specific to the Message) of the SoundRecording within the Release which contains it. This is a LocalResourceAnchor starting with the letter A.
     *
     * @return string
     */
    public function getResourceReference()
    {
        return $this->resourceReference;
    }

    /**
     * Sets a new resourceReference
     *
     * The Identifier (specific to the Message) of the SoundRecording within the Release which contains it. This is a LocalResourceAnchor starting with the letter A.
     *
     * @param string $resourceReference
     * @return self
     */
    public function setResourceReference($resourceReference)
    {
        $this->resourceReference = $resourceReference;
        return $this;
    }

    /**
     * Gets as referenceTitle
     *
     * A Composite containing details of the ReferenceTitle of the SoundRecording.
     *
     * @return \DDEX\DSR\DSR_420\ReferenceTitleType
     */
    public function getReferenceTitle()
    {
        return $this->referenceTitle;
    }

    /**
     * Sets a new referenceTitle
     *
     * A Composite containing details of the ReferenceTitle of the SoundRecording.
     *
     * @param \DDEX\DSR\DSR_420\ReferenceTitleType $referenceTitle
     * @return self
     */
    public function setReferenceTitle(\DDEX\DSR\DSR_420\ReferenceTitleType $referenceTitle)
    {
        $this->referenceTitle = $referenceTitle;
        return $this;
    }

    /**
     * Gets as instrumentationDescription
     *
     * A Composite containing a Description of the Type of instrumentation of the MusicalWork(s) in the SoundRecording.
     *
     * @return \DDEX\DSR\DSR_420\DescriptionType
     */
    public function getInstrumentationDescription()
    {
        return $this->instrumentationDescription;
    }

    /**
     * Sets a new instrumentationDescription
     *
     * A Composite containing a Description of the Type of instrumentation of the MusicalWork(s) in the SoundRecording.
     *
     * @param \DDEX\DSR\DSR_420\DescriptionType $instrumentationDescription
     * @return self
     */
    public function setInstrumentationDescription(?\DDEX\DSR\DSR_420\DescriptionType $instrumentationDescription = null)
    {
        $this->instrumentationDescription = $instrumentationDescription;
        return $this;
    }

    /**
     * Gets as isMedley
     *
     * The Flag indicating whether the SoundRecording is a Medley (=True) or not (=False).
     *
     * @return bool
     */
    public function getIsMedley()
    {
        return $this->isMedley;
    }

    /**
     * Sets a new isMedley
     *
     * The Flag indicating whether the SoundRecording is a Medley (=True) or not (=False).
     *
     * @param bool $isMedley
     * @return self
     */
    public function setIsMedley($isMedley)
    {
        $this->isMedley = $isMedley;
        return $this;
    }

    /**
     * Gets as isPotpourri
     *
     * The Flag indicating whether the SoundRecording is a Potpourri (=True) or not (=False).
     *
     * @return bool
     */
    public function getIsPotpourri()
    {
        return $this->isPotpourri;
    }

    /**
     * Sets a new isPotpourri
     *
     * The Flag indicating whether the SoundRecording is a Potpourri (=True) or not (=False).
     *
     * @param bool $isPotpourri
     * @return self
     */
    public function setIsPotpourri($isPotpourri)
    {
        $this->isPotpourri = $isPotpourri;
        return $this;
    }

    /**
     * Gets as isInstrumental
     *
     * The Flag indicating whether the SoundRecording is instrumental (=True) or not (=False).
     *
     * @return bool
     */
    public function getIsInstrumental()
    {
        return $this->isInstrumental;
    }

    /**
     * Sets a new isInstrumental
     *
     * The Flag indicating whether the SoundRecording is instrumental (=True) or not (=False).
     *
     * @param bool $isInstrumental
     * @return self
     */
    public function setIsInstrumental($isInstrumental)
    {
        $this->isInstrumental = $isInstrumental;
        return $this;
    }

    /**
     * Gets as isBackground
     *
     * The Flag indicating whether the SoundRecording is used as background to other audio or audiovisual material (=True) or not (=False).
     *
     * @return bool
     */
    public function getIsBackground()
    {
        return $this->isBackground;
    }

    /**
     * Sets a new isBackground
     *
     * The Flag indicating whether the SoundRecording is used as background to other audio or audiovisual material (=True) or not (=False).
     *
     * @param bool $isBackground
     * @return self
     */
    public function setIsBackground($isBackground)
    {
        $this->isBackground = $isBackground;
        return $this;
    }

    /**
     * Gets as isHiddenResource
     *
     * The Flag indicating whether the SoundRecording is hidden in some way from the Consumer (=True) or not (=False).
     *
     * @return bool
     */
    public function getIsHiddenResource()
    {
        return $this->isHiddenResource;
    }

    /**
     * Sets a new isHiddenResource
     *
     * The Flag indicating whether the SoundRecording is hidden in some way from the Consumer (=True) or not (=False).
     *
     * @param bool $isHiddenResource
     * @return self
     */
    public function setIsHiddenResource($isHiddenResource)
    {
        $this->isHiddenResource = $isHiddenResource;
        return $this;
    }

    /**
     * Gets as isBonusResource
     *
     * The Flag indicating whether the SoundRecording is additional to those on the original Release of which this is a Version (=True) or not (=False).
     *
     * @return bool
     */
    public function getIsBonusResource()
    {
        return $this->isBonusResource;
    }

    /**
     * Sets a new isBonusResource
     *
     * The Flag indicating whether the SoundRecording is additional to those on the original Release of which this is a Version (=True) or not (=False).
     *
     * @param bool $isBonusResource
     * @return self
     */
    public function setIsBonusResource($isBonusResource)
    {
        $this->isBonusResource = $isBonusResource;
        return $this;
    }

    /**
     * Gets as isComputerGenerated
     *
     * The Flag indicating whether the SoundRecording is generated by a computer (=True) or not (=False).
     *
     * @return bool
     */
    public function getIsComputerGenerated()
    {
        return $this->isComputerGenerated;
    }

    /**
     * Sets a new isComputerGenerated
     *
     * The Flag indicating whether the SoundRecording is generated by a computer (=True) or not (=False).
     *
     * @param bool $isComputerGenerated
     * @return self
     */
    public function setIsComputerGenerated($isComputerGenerated)
    {
        $this->isComputerGenerated = $isComputerGenerated;
        return $this;
    }

    /**
     * Gets as performerInformationRequired
     *
     * A Flag indicating whether performer information is required (=True) or not (=False) when communicating details of the SoundRecording.
     *
     * @return bool
     */
    public function getPerformerInformationRequired()
    {
        return $this->performerInformationRequired;
    }

    /**
     * Sets a new performerInformationRequired
     *
     * A Flag indicating whether performer information is required (=True) or not (=False) when communicating details of the SoundRecording.
     *
     * @param bool $performerInformationRequired
     * @return self
     */
    public function setPerformerInformationRequired($performerInformationRequired)
    {
        $this->performerInformationRequired = $performerInformationRequired;
        return $this;
    }

    /**
     * Gets as languageOfPerformance
     *
     * The Language of the Performance recorded in the SoundRecording (represented by an ISO 639-2 LanguageCode).
     *
     * @return string
     */
    public function getLanguageOfPerformance()
    {
        return $this->languageOfPerformance;
    }

    /**
     * Sets a new languageOfPerformance
     *
     * The Language of the Performance recorded in the SoundRecording (represented by an ISO 639-2 LanguageCode).
     *
     * @param string $languageOfPerformance
     * @return self
     */
    public function setLanguageOfPerformance($languageOfPerformance)
    {
        $this->languageOfPerformance = $languageOfPerformance;
        return $this;
    }

    /**
     * Gets as duration
     *
     * The Duration of the SoundRecording (using the ISO 8601:2004 PT[[hhH]mmM]ssS format, where lower case characters indicate variables, upper case characters are part of the xs:string, e.g. one hour, two minutes and three seconds would be PT1H2M3S).
     *
     * @return \DateInterval
     */
    public function getDuration()
    {
        return $this->duration;
    }

    /**
     * Sets a new duration
     *
     * The Duration of the SoundRecording (using the ISO 8601:2004 PT[[hhH]mmM]ssS format, where lower case characters indicate variables, upper case characters are part of the xs:string, e.g. one hour, two minutes and three seconds would be PT1H2M3S).
     *
     * @param \DateInterval $duration
     * @return self
     */
    public function setDuration(\DateInterval $duration)
    {
        $this->duration = $duration;
        return $this;
    }

    /**
     * Gets as rightsAgreementId
     *
     * A Composite containing details of Identifiers of a License, Claim, RightShare or contract for the MusicalWork(s) used in the SoundRecording.
     *
     * @return \DDEX\DSR\DSR_420\RightsAgreementIdType
     */
    public function getRightsAgreementId()
    {
        return $this->rightsAgreementId;
    }

    /**
     * Sets a new rightsAgreementId
     *
     * A Composite containing details of Identifiers of a License, Claim, RightShare or contract for the MusicalWork(s) used in the SoundRecording.
     *
     * @param \DDEX\DSR\DSR_420\RightsAgreementIdType $rightsAgreementId
     * @return self
     */
    public function setRightsAgreementId(?\DDEX\DSR\DSR_420\RightsAgreementIdType $rightsAgreementId = null)
    {
        $this->rightsAgreementId = $rightsAgreementId;
        return $this;
    }

    /**
     * Adds as resourceMusicalWorkReference
     *
     * A Composite containing details of one or more MusicalWorks contained in the SoundRecording.
     *
     * @return self
     * @param \DDEX\DSR\DSR_420\ResourceMusicalWorkReferenceType $resourceMusicalWorkReference
     */
    public function addToResourceMusicalWorkReferenceList(\DDEX\DSR\DSR_420\ResourceMusicalWorkReferenceType $resourceMusicalWorkReference)
    {
        $this->resourceMusicalWorkReferenceList[] = $resourceMusicalWorkReference;
        return $this;
    }

    /**
     * isset resourceMusicalWorkReferenceList
     *
     * A Composite containing details of one or more MusicalWorks contained in the SoundRecording.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetResourceMusicalWorkReferenceList($index)
    {
        return isset($this->resourceMusicalWorkReferenceList[$index]);
    }

    /**
     * unset resourceMusicalWorkReferenceList
     *
     * A Composite containing details of one or more MusicalWorks contained in the SoundRecording.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetResourceMusicalWorkReferenceList($index)
    {
        unset($this->resourceMusicalWorkReferenceList[$index]);
    }

    /**
     * Gets as resourceMusicalWorkReferenceList
     *
     * A Composite containing details of one or more MusicalWorks contained in the SoundRecording.
     *
     * @return \DDEX\DSR\DSR_420\ResourceMusicalWorkReferenceType[]
     */
    public function getResourceMusicalWorkReferenceList()
    {
        return $this->resourceMusicalWorkReferenceList;
    }

    /**
     * Sets a new resourceMusicalWorkReferenceList
     *
     * A Composite containing details of one or more MusicalWorks contained in the SoundRecording.
     *
     * @param \DDEX\DSR\DSR_420\ResourceMusicalWorkReferenceType[] $resourceMusicalWorkReferenceList
     * @return self
     */
    public function setResourceMusicalWorkReferenceList(array $resourceMusicalWorkReferenceList = null)
    {
        $this->resourceMusicalWorkReferenceList = $resourceMusicalWorkReferenceList;
        return $this;
    }

    /**
     * Adds as resourceContainedResourceReference
     *
     * A Composite containing details of ResourceContainedResourceReferences referring to a Resource that is contained in the current SoundRecording.
     *
     * @return self
     * @param \DDEX\DSR\DSR_420\ResourceContainedResourceReferenceType $resourceContainedResourceReference
     */
    public function addToResourceContainedResourceReferenceList(\DDEX\DSR\DSR_420\ResourceContainedResourceReferenceType $resourceContainedResourceReference)
    {
        $this->resourceContainedResourceReferenceList[] = $resourceContainedResourceReference;
        return $this;
    }

    /**
     * isset resourceContainedResourceReferenceList
     *
     * A Composite containing details of ResourceContainedResourceReferences referring to a Resource that is contained in the current SoundRecording.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetResourceContainedResourceReferenceList($index)
    {
        return isset($this->resourceContainedResourceReferenceList[$index]);
    }

    /**
     * unset resourceContainedResourceReferenceList
     *
     * A Composite containing details of ResourceContainedResourceReferences referring to a Resource that is contained in the current SoundRecording.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetResourceContainedResourceReferenceList($index)
    {
        unset($this->resourceContainedResourceReferenceList[$index]);
    }

    /**
     * Gets as resourceContainedResourceReferenceList
     *
     * A Composite containing details of ResourceContainedResourceReferences referring to a Resource that is contained in the current SoundRecording.
     *
     * @return \DDEX\DSR\DSR_420\ResourceContainedResourceReferenceType[]
     */
    public function getResourceContainedResourceReferenceList()
    {
        return $this->resourceContainedResourceReferenceList;
    }

    /**
     * Sets a new resourceContainedResourceReferenceList
     *
     * A Composite containing details of ResourceContainedResourceReferences referring to a Resource that is contained in the current SoundRecording.
     *
     * @param \DDEX\DSR\DSR_420\ResourceContainedResourceReferenceType[] $resourceContainedResourceReferenceList
     * @return self
     */
    public function setResourceContainedResourceReferenceList(array $resourceContainedResourceReferenceList = null)
    {
        $this->resourceContainedResourceReferenceList = $resourceContainedResourceReferenceList;
        return $this;
    }

    /**
     * Gets as creationDate
     *
     * A Composite containing details of the Date and Place of the Event in which the SoundRecording was created.
     *
     * @return \DDEX\DSR\DSR_420\EventDateType
     */
    public function getCreationDate()
    {
        return $this->creationDate;
    }

    /**
     * Sets a new creationDate
     *
     * A Composite containing details of the Date and Place of the Event in which the SoundRecording was created.
     *
     * @param \DDEX\DSR\DSR_420\EventDateType $creationDate
     * @return self
     */
    public function setCreationDate(?\DDEX\DSR\DSR_420\EventDateType $creationDate = null)
    {
        $this->creationDate = $creationDate;
        return $this;
    }

    /**
     * Gets as masteredDate
     *
     * A Composite containing details of the Date and Place of the Event in which the SoundRecording was originally mastered (either in analogue or digital form).
     *
     * @return \DDEX\DSR\DSR_420\EventDateType
     */
    public function getMasteredDate()
    {
        return $this->masteredDate;
    }

    /**
     * Sets a new masteredDate
     *
     * A Composite containing details of the Date and Place of the Event in which the SoundRecording was originally mastered (either in analogue or digital form).
     *
     * @param \DDEX\DSR\DSR_420\EventDateType $masteredDate
     * @return self
     */
    public function setMasteredDate(?\DDEX\DSR\DSR_420\EventDateType $masteredDate = null)
    {
        $this->masteredDate = $masteredDate;
        return $this;
    }

    /**
     * Adds as soundRecordingDetailsByTerritory
     *
     * A Composite containing details of Descriptors and other attributes of the SoundRecording which may vary according to Territory of release.
     *
     * @return self
     * @param \DDEX\DSR\DSR_420\SoundRecordingDetailsByTerritoryType $soundRecordingDetailsByTerritory
     */
    public function addToSoundRecordingDetailsByTerritory(\DDEX\DSR\DSR_420\SoundRecordingDetailsByTerritoryType $soundRecordingDetailsByTerritory)
    {
        $this->soundRecordingDetailsByTerritory[] = $soundRecordingDetailsByTerritory;
        return $this;
    }

    /**
     * isset soundRecordingDetailsByTerritory
     *
     * A Composite containing details of Descriptors and other attributes of the SoundRecording which may vary according to Territory of release.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetSoundRecordingDetailsByTerritory($index)
    {
        return isset($this->soundRecordingDetailsByTerritory[$index]);
    }

    /**
     * unset soundRecordingDetailsByTerritory
     *
     * A Composite containing details of Descriptors and other attributes of the SoundRecording which may vary according to Territory of release.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetSoundRecordingDetailsByTerritory($index)
    {
        unset($this->soundRecordingDetailsByTerritory[$index]);
    }

    /**
     * Gets as soundRecordingDetailsByTerritory
     *
     * A Composite containing details of Descriptors and other attributes of the SoundRecording which may vary according to Territory of release.
     *
     * @return \DDEX\DSR\DSR_420\SoundRecordingDetailsByTerritoryType[]
     */
    public function getSoundRecordingDetailsByTerritory()
    {
        return $this->soundRecordingDetailsByTerritory;
    }

    /**
     * Sets a new soundRecordingDetailsByTerritory
     *
     * A Composite containing details of Descriptors and other attributes of the SoundRecording which may vary according to Territory of release.
     *
     * @param \DDEX\DSR\DSR_420\SoundRecordingDetailsByTerritoryType[] $soundRecordingDetailsByTerritory
     * @return self
     */
    public function setSoundRecordingDetailsByTerritory(array $soundRecordingDetailsByTerritory)
    {
        $this->soundRecordingDetailsByTerritory = $soundRecordingDetailsByTerritory;
        return $this;
    }

    /**
     * Gets as uRL
     *
     * A URL from which the SoundRecording was sold.
     *
     * @return string
     */
    public function getURL()
    {
        return $this->uRL;
    }

    /**
     * Sets a new uRL
     *
     * A URL from which the SoundRecording was sold.
     *
     * @param string $uRL
     * @return self
     */
    public function setURL($uRL)
    {
        $this->uRL = $uRL;
        return $this;
    }
}

