<?xml version="1.0" encoding="UTF-8"?>
<!-- SCOW Version v0.9.3 2407 -->
<xs:schema xmlns:ern-c-ws="http://ddex.net/xml/ern-c-ws/18"
           xmlns:avs="http://ddex.net/xml/allowed-value-sets"
           xmlns:ds="http://www.w3.org/2000/09/xmldsig#"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://ddex.net/xml/ern-c-ws/18"
           elementFormDefault="unqualified"
           attributeFormDefault="unqualified">
   <xs:import namespace="http://ddex.net/xml/allowed-value-sets"
              schemaLocation="http://ddex.net/xml/allowed-value-sets/allowed-value-sets.xsd"/>
   <xs:annotation>
      <xs:documentation>© 2006-2024 Digital Data Exchange, LLC (DDEX)</xs:documentation>
      <xs:documentation>This XML Schema Definition file is, together with all DDEX standards, subject to two licences: If you wish to evaluate whether the standard meets your needs please have a look at the Evaluation Licence provided on page one of every DDEX standard. If you want to implement and use this DDEX standard, please take out an Implementation Licence. For details please go to http://ddex.net/apply-ddex-implementation-licence.</xs:documentation>
   </xs:annotation>
   <xs:element name="AcknowledgementMessage">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Message in the ERN Standard (Part 4: Choreography for Web Services).</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element name="MessageHeader" type="ern-c-ws:MessageHeader">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The MessageHeader for the AcknowledgementMessage.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="ReleaseStatus"
                        minOccurs="0"
                        maxOccurs="unbounded"
                        type="ern-c-ws:ReleaseStatus">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of the Release status.</xs:documentation>
               </xs:annotation>
            </xs:element>
         </xs:sequence>
         <xs:attribute name="AvsVersionId" type="xs:string" use="required">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The Identifier of the Version of the AllowedValueSets used for the Message. This is represented in an XML schema as an XML Attribute.</xs:documentation>
            </xs:annotation>
         </xs:attribute>
      </xs:complexType>
   </xs:element>
   <xs:element name="Feed">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Message in the ERN Choreography Standard for an atom feed defined by W3C/IETF. The Atom feed construct is defined in section 4.1.1 of the format spec.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:choice minOccurs="3" maxOccurs="unbounded">
            <xs:element name="author"
                        minOccurs="0"
                        maxOccurs="unbounded"
                        type="ern-c-ws:Person">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of the Name, Identifier and Role(s) of an author of a Resource.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="category"
                        minOccurs="0"
                        maxOccurs="unbounded"
                        type="ern-c-ws:Category">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of a category.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="contributor"
                        minOccurs="0"
                        maxOccurs="unbounded"
                        type="ern-c-ws:Person">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of the Name, Identifier and Role(s) of a contributor to a Resource.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="generator" minOccurs="0" type="ern-c-ws:Generator">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of a generator.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="icon" minOccurs="0" type="ern-c-ws:Icon">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of an icon.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="id" type="ern-c-ws:Id">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of an ID.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="link"
                        minOccurs="0"
                        maxOccurs="unbounded"
                        type="ern-c-ws:Link">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of a link.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="logo" minOccurs="0" type="ern-c-ws:Logo">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of a logo.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="rights" minOccurs="0" type="ern-c-ws:Text">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of rights.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="subtitle" minOccurs="0" type="ern-c-ws:Text">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of a subtitle.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="title" type="ern-c-ws:Text">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of a title.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="updated" type="ern-c-ws:DateTime">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of an update.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="entry"
                        minOccurs="0"
                        maxOccurs="unbounded"
                        type="ern-c-ws:Entry">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of an entry.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
         </xs:choice>
         <xs:anyAttribute namespace="##other"/>
      </xs:complexType>
   </xs:element>
   <xs:complexType name="Acknowledgement">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of an acknowledgement.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="MessageType" type="avs:ErnTestMessageType">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The Type of Message.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="BatchId" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An Identifier of the Batch.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageId" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An Identifier of the Message.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageStatus"
                     maxOccurs="unbounded"
                     type="ern-c-ws:MessageStatus">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the Message Status.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="FormalIdentifier">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of an Identifier that is formally used.</xs:documentation>
      </xs:annotation>
      <xs:choice>
         <xs:element name="ResourceId" type="ern-c-ws:ResourceId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a ResourceId.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ReleaseId" type="ern-c-ws:ReleaseId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a ReleaseId.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="WorkId" type="ern-c-ws:MusicalWorkId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a MusicalWorkId.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="PartyId" type="ern-c-ws:DetailedPartyId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a PartyId.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:choice>
   </xs:complexType>
   <xs:complexType name="MessageStatus">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a Message Status.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="Status" type="ern-c-ws:Status">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the status of the Message.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="Information" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Status text for the Message.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="ProposedActionType">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a ProposedActionType.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="avs:ErncProposedActionType">
            <xs:attribute name="Namespace" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Namespace of the ProposedActionType. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
            <xs:attribute name="UserDefinedValue" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A UserDefined value of the ProposedActionType. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="ProprietaryIdMapping">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier mapping.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="FormalIdentifier" type="ern-c-ws:FormalIdentifier">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of an Identifier that is formally used.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ProprietaryId" type="ern-c-ws:ProprietaryIdWithOptionalAttribute">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier for the above Identifier.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="LandingPage"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A URL for the WebPage where the item identified by the Identifier can be found on the DSP's system.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="ProprietaryIdWithOptionalAttribute">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier.</xs:documentation>
         <xs:documentation source="ddex:Comment">Explanatory Note: This Composite is named ProprietaryIdWithOptionalAttribute to disambiguate it from the basic ProprietaryId Composite.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="Namespace" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Namespace of the ProprietaryIdentifier. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="ReleaseStatus">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a Release status.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="ReleaseId" type="ern-c-ws:ReleaseId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of ReleaseIds. If available, a GRid has to be used. If the Release is an abstraction of a complete PhysicalProduct (such as a CD Album), the ICPN of the PhysicalProduct may be used instead.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ReleaseStatus" type="ern-c-ws:SupplyChainStatus">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the status of the Release.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ErrorText" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Comment about the Message. This is solely to aid the MessageRecipient of the Message to resolve the issues complained about.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ProposedActionType"
                     minOccurs="0"
                     type="ern-c-ws:ProposedActionType">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the Type of action that is proposed by the MessageSender.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ManualCheckRequired" minOccurs="0" type="xs:boolean">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Flag indicating whether the sender just needs to resend the same material again (=false) or whether someone needs to look at the material before the re-delivery is done (=true).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ProprietaryIdMapping"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:ProprietaryIdMapping">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier mapping.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="AffectedResource"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:ResourceId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of ResourceIds for the Resources that are affected.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="Acknowledgement"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:Acknowledgement">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of an acknowledgement.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="Claimant"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:PartyDescriptor">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a Party that has also claimed the same SoundRecording for the same territory and time.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="ResourceId">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of ResourceIds.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="ISRC" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The ISRC (International Standard Recording Code as defined in ISO 3901) for the Resource. An ISRC comprises four parts: two characters, followed by three alphanumeric characters, then two digits and five digits. DDEX will enforce the syntax [a-zA-Z]{2}[a-zA-Z0-9]{3}[0-9]{7} in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ISMN" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The ISMN (International Standard Music Number defined in ISO 10957) for the Resource. An ISMN is a thirteen-digit number. Pre-2008 ISMNs, which had 10 characters and are now deprecated, are converted by replacing the initial letter ('M') with '979-0'. DDEX will enforce the syntax 979[0-9]{9}[X0-9] in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ISAN" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The ISAN (International Standard Audiovisual Number as defined in ISO 15706) for the Resource. An ISAN comprises four blocks of four hexadecimal charaters followed by a check character. DDEX will enforce the syntax [A-F0-9]{12} in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="VISAN" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The V-ISAN (Version Identifier of an International Standard Audiovisual Number as defined in ISO 15706-2) for the Resource. A V-ISAN comprises four blocks of four hexadecimal charaters followed by a check character, followed by two further blocks of four hexadecimal characters, followed by a further check character. DDEX will enforce the syntax [A-F0-9]{24} in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ISBN" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The ISBN (International Standard Book Number defined in ISO 2108) for the Resource. An ISBN is a 13-digit number. Pre-2007, ISBNs, which had 10-digits and are now deprecated, are converted by adding the prefix '978' and re-calculating the check character. DDEX will enforce the syntax 97[8-9][0-9]{9}[X0-9] in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ISSN" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The ISSN (International Standard Serial Number defined in ISO 3297) for the Resource. An ISSN comprises two groups of four digits, separated by a hyphen and a control digit. DDEX will enforce the syntax [0-9]{4}-[0-9]{3}[X0-9] in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="SICI" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The SICI (Serial Item and Contribution Identifier defined in ANSI/NISO Z39.56-199) for the Resource. DDEX will enforce the syntax [0-9]{4}-[0-9]{3}[X0-9].+ in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="CatalogNumber" minOccurs="0" type="ern-c-ws:CatalogNumber">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the CatalogNumber of the Resource.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ProprietaryId"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:ProprietaryId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier of the Resource.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Status">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a Message Status.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="avs:ErncFileStatus">
            <xs:attribute name="Namespace" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Namespace of the Message Status. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
            <xs:attribute name="UserDefinedValue" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A UserDefined value of the Message Status. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="Category">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a category. The Atom cagegory construct is defined in section 4.2.2 of the format spec.</xs:documentation>
      </xs:annotation>
      <xs:attribute name="term" type="xs:string" use="required">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The term. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="scheme" type="xs:anyURI">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The scheme. This is represented in an XML schema as an XML Attribute of type AnyURI.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="label" type="xs:string">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The label. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:anyAttribute namespace="##other"/>
   </xs:complexType>
   <xs:complexType name="Content" mixed="true">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a content. The Atom content construct is defined in section 4.1.3 of the format spec.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="type" type="xs:string">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The type. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="src" type="xs:anyURI">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The source. This is represented in an XML schema as an XML Attribute of type AnyURI.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:anyAttribute namespace="##other"/>
   </xs:complexType>
   <xs:complexType name="DateTime">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a published.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:dateTime">
            <xs:anyAttribute namespace="##other"/>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="Entry">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Message in the ERN Choreography Standard for an atom entry defined by W3C/IETF. The Atom entry construct is defined in section 4.1.2 of the format spec.</xs:documentation>
      </xs:annotation>
      <xs:choice maxOccurs="unbounded">
         <xs:element name="author"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:Person">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the Name, Identifier and Role(s) of an author of a Resource.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="category"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:Category">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a category.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="content" minOccurs="0" type="ern-c-ws:Content">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a content.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="contributor"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:Person">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the Name, Identifier and Role(s) of a contributor to a Resource.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="id" type="ern-c-ws:Id">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of an ID.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="link"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:Link">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a link.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="published" minOccurs="0" type="ern-c-ws:DateTime">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a published.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="rights" minOccurs="0" type="ern-c-ws:Text">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of rights.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="source" minOccurs="0" type="ern-c-ws:Source">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a source.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="summary" minOccurs="0" type="ern-c-ws:Text">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a summary.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="title" type="ern-c-ws:Text">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a title.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="updated" type="ern-c-ws:DateTime">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of an update.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ReleaseType" minOccurs="0" type="avs:ReleaseType_ERN4">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Type of Release according to its content, Duration and/or number of components. Note: a ReleaseType is the form in which a ReleaseCreator anticipates offering a Release to Consumers.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ReleaseId" minOccurs="0" type="ern-c-ws:ReleaseIdForEntry">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of ReleaseIds. If available, a GRid has to be used. If the Release contains only one SoundRecording, the ISRC of the SoundRecording may be used instead. If the Release is an abstraction of a complete PhysicalProduct (such as a CD Album), the ICPN of the PhysicalProduct may be used instead.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="DisplayArtistName"
                     minOccurs="0"
                     type="ern-c-ws:DisplayArtistNameWithDefault">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing the Name to be used by a DSP when presenting Artist details of the Release to a Consumer.</xs:documentation>
               <xs:documentation source="ddex:Comment">Further Reading: https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/guidance-on-contributors%2C-artists-and-writers/communicating-displayartists-and-displayartistname</xs:documentation>
               <xs:documentation source="ddex:Comment">Further Reading: https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/guidance-on-contributors%2C-artists-and-writers/displayartistnames-for-releases-and-resources</xs:documentation>
               <xs:documentation source="ddex:Comment">Further Reading: https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/guidance-on-contributors%2C-artists-and-writers/information-on-displayartists%2C-displayartistnames%2C-contributors-and-indirectcontributors</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:choice>
      <xs:attribute name="AvsVersionId" type="xs:string" use="required">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The Identifier of the Version of the AllowedValueSets used for the Message. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:anyAttribute namespace="##other"/>
   </xs:complexType>
   <xs:complexType name="Generator">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a generator. The Atom generator element is defined in section 4.2.4 of the format spec.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="uri" type="xs:anyURI">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The URI. This is represented in an XML schema as an XML Attribute of type AnyURI.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
            <xs:attribute name="version" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Identifier of the Version of the generator. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
            <xs:anyAttribute namespace="##other"/>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="Icon">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of an icon. The Atom icon construct is defined in section 4.2.5 of the format spec.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:anyURI">
            <xs:anyAttribute namespace="##other"/>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="Id">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of an ID. The Atom id construct is defined in section 4.2.6 of the format spec.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:anyURI">
            <xs:anyAttribute namespace="##other"/>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="Link" mixed="true">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a link. The Atom link construct is defined in section 3.4 of the format spec.</xs:documentation>
      </xs:annotation>
      <xs:attribute name="href" type="xs:anyURI" use="required">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The href. This is represented in an XML schema as an XML Attribute of type AnyURI.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="rel" type="xs:string">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The rel. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="type" type="xs:string">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The type. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="hreflang" type="xs:NMTOKEN">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The href lang. This is represented in an XML schema as an XML Attribute of type NMTOKEN.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="title" type="xs:string">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The title. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:attribute name="length" type="xs:positiveInteger">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The length. This is represented in an XML schema as an XML Attribute of type PositiveInteger.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:anyAttribute namespace="##other"/>
   </xs:complexType>
   <xs:complexType name="Logo">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a logo. The Atom logo construct is defined in section 4.2.8 of the format spec.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:anyURI">
            <xs:anyAttribute namespace="##other"/>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="Person">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of the Name, Identifier and Role(s) of a Party related to a Resource. The Atom person construct is defined in section 3.2 of the format spec.</xs:documentation>
      </xs:annotation>
      <xs:choice maxOccurs="unbounded">
         <xs:element name="name" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Name of the person.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="uri" minOccurs="0" type="ern-c-ws:URI">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a URI.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="email" minOccurs="0">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of an Email address. This is a NormalizedString.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:normalizedString">
                  <xs:pattern value="\w+@(\w+\.)+\w+"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:any namespace="##other"/>
      </xs:choice>
      <xs:anyAttribute namespace="##other"/>
   </xs:complexType>
   <xs:complexType name="ReleaseIdForEntry">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a ReleaseId. If available, a GRid should always to be used. If the Release is an abstraction of a complete PhysicalProduct (such as a CD Album), the ICPN of the PhysicalProduct may be used instead.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="GRid" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The GRid identifying the Release. This is the preferred Element and is mandatory if a GRid is available. A GRid comprises four parts: the xs:string 'A1', followed by five alphanumeric characters, ten alphanumeric characters and and one alphanumeric character. DDEX will enforce the syntax [a-zA-Z0-9]{18} in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ISRC" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The ISRC (International Standard Recording Code as defined in ISO 3901) used as proxy for identification of the Release. Only applicable when the Release only contains one SoundRecording or one MusicalWorkVideo. An ISRC comprises four parts: two characters, followed by three alphanumeric characters, then two digits and five digits. DDEX will enforce the syntax [a-zA-Z]{2}[a-zA-Z0-9]{3}[0-9]{7} in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ICPN" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An ICPN used as proxy for identification of the Release. If the Release is an abstraction of a PhysicalProduct, this may be the ICPN identifying the complete PhysicalProduct. An ICPN can be a UPC, EAN, JAN or any other bar code identifying, for example, the abstracted PhysicalProduct.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="CatalogNumber" minOccurs="0" type="ern-c-ws:CatalogNumber">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the CatalogNumber of the Release.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ProprietaryId"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:ProprietaryId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier of the Release.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Source">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a source. The Atom source construct is defined in section 4.2.11 of the format spec.</xs:documentation>
      </xs:annotation>
      <xs:choice maxOccurs="unbounded">
         <xs:element name="author"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:Person">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the Name, Identifier and Role(s) of an author of a Resource.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="category"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:Category">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a category.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="contributor"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:Person">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the Name, Identifier and Role(s) of a contributor to a Resource.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="generator" minOccurs="0" type="ern-c-ws:Generator">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a generator.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="icon" minOccurs="0" type="ern-c-ws:Icon">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of an icon.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="id" minOccurs="0" type="ern-c-ws:Id">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of an ID.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="link"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:Link">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a link.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="logo" minOccurs="0" type="ern-c-ws:Logo">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a logo.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="rights" minOccurs="0" type="ern-c-ws:Text">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of rights.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="subtitle" minOccurs="0" type="ern-c-ws:Text">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a subtitle.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="title" minOccurs="0" type="ern-c-ws:Text">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a title.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="updated" minOccurs="0" type="ern-c-ws:DateTime">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of an update.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:any namespace="##other" minOccurs="0" maxOccurs="unbounded"/>
      </xs:choice>
      <xs:anyAttribute namespace="##other"/>
   </xs:complexType>
   <xs:complexType name="Text" mixed="true">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a text. The Atom text construct is defined in section 3.1 of the format spec.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:any namespace="http://www.w3.org/1999/xhtml" minOccurs="0"/>
      </xs:sequence>
      <xs:attribute name="type" type="avs:TextType_ATOM">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The type. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
      <xs:anyAttribute namespace="##other"/>
   </xs:complexType>
   <xs:complexType name="URI">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a URI.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:anyURI">
            <xs:anyAttribute namespace="##other"/>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="CatalogNumber">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a CatalogNumber.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="Namespace" type="xs:string" use="required">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Namespace of the CatalogNumber. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="DetailedPartyId">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a PartyId.</xs:documentation>
         <xs:documentation source="ddex:Comment">Explanatory Note: This Composite is named DetailedPartyId to disambiguate it from the basic PartyId Composite.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="ISNI" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An International Standard Name Identifier, the ISO 27729 Standard Identifier for names. DDEX will enforce the syntax [0-9]{15}[X0-9] in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="DPID" minOccurs="0">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An Identifier of a Party according to the DdexPartyId standard DDEX-DPID.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:pattern value="PADPIDA[a-zA-Z0-9]+"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:element name="IpiNameNumber" minOccurs="0">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An Interested Party Identifier, a CISAC standard Identifier. An IpiNameNumber comprises 11 digits.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:pattern value="[0-9]{11}"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:element name="IPN" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An International Performer Number, an IPDA Identifier.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="CisacSocietyId" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A CISAC Society Identifier, a CISAC standard Identifier for music rights societies.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ProprietaryId"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:ProprietaryId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier of the Party.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="DisplayArtistNameWithDefault">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a DisplayArtistName.</xs:documentation>
         <xs:documentation source="ddex:Comment">Explanatory Note: This Composite is named DisplayArtistNameWithDefault to disambiguate it from the basic DisplayArtistName Composite.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="LanguageAndScriptCode" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Language and script of the Name as defined in IETF RfC 5646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-script][-region][-variant]. A list of common language/script combinations has been published in the Language Metadata Table (LMT) at https://www.mesaonline.org/lmt by the Media &amp; Entertainment Services Alliance. Other language/script combinations allowed by IETF RfC 5646 are also valid. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
            <xs:attribute name="ApplicableTerritoryCode" type="avs:CurrentTerritoryCode">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Territory to which the Name applies. The use of ISO TerritoryCodes (or the term 'Worldwide') is strongly encouraged; TIS TerritoryCodes should only be used if both MessageSender and MessageRecipient are familiar with this standard. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
            <xs:attribute name="IsDefault" type="xs:boolean">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Flag indicating whether this Composite provides default values (=true). This Flag should not be set if this is not the case. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="MessageAuditTrail">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing information about Parties in between the original MessageSender and ultimate MessageRecipient.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="MessageAuditTrailEvent"
                     maxOccurs="unbounded"
                     type="ern-c-ws:MessageAuditTrailEvent">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a Party handling the Message and the Time at which the handling took place.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="MessageAuditTrailEvent">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a Party handling a Message and the Time at which the handling took place.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="MessagingPartyDescriptor"
                     type="ern-c-ws:MessagingPartyWithoutCode">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a MessagingParty.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="DateTime" type="xs:dateTime">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The DateTime at which the Message was handled by the MessagingParty (the only allowed format is ISO 8601: YYYY-MM-DDThh:mm:ssTZD).</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="MessageHeader">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite placed at the beginning of each DdexMessage providing information about the Message, such as MessageSender, MessageRecipient and a Message creation time stamp.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="MessageThreadId" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A xs:string used to uniquely identify the thread of Messages of which the current Message is a part. The MessageThreadId shall be, in combination with the DdexPartyId (DPID) of the MessageSender, globally unique. Thus, a MessageSender shall never re-use a MessageThreadId. One example of such a 'thread' is the chain of NewReleaseMessages being sent from ReleaseCreator to wholesale ReleaseDistributor 1 to retail DSP when communicating information about the same Release(s). A common MessageThreadId will allow all these messages to be tied together.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageId" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A xs:string used to uniquely identify the current Message. The MessageId shall be, in combination with the DdexPartyId (DPID) of the MessageSender, globally unique. Thus, a MessageSender shall never re-use a MessageId.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageFileName" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The FileName, possibly including the FilePath, of the File containing the current Message.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageSender" type="ern-c-ws:MessagingPartyWithoutCode">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the MessageSender.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="SentOnBehalfOf"
                     minOccurs="0"
                     type="ern-c-ws:MessagingPartyWithoutCode">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the Party on whose behalf the Message is sent.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageRecipient"
                     maxOccurs="unbounded"
                     type="ern-c-ws:MessagingPartyWithoutCode">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the MessageRecipient. Note that if multiple MessageRecipients are provided, all of them will be able to read this information.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="SentAsRequestedBy"
                     minOccurs="0"
                     type="ern-c-ws:MessagingPartyWithoutCode">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the Party on whose request the Message is sent.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageCreatedDateTime" type="xs:dateTime">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The DateTime on which the Message was created (the only allowed format is RFC 3339: YYYY-MM-DDThh:mm:ssTZD, where TZD stands for time zone designator, which can be the letter Z or an offset from UTC in the format +hh:mm or -hh:mm).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageAuditTrail"
                     minOccurs="0"
                     type="ern-c-ws:MessageAuditTrail">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing information about Parties in between the original MessageSender and ultimate MessageRecipient.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageControlType"
                     minOccurs="0"
                     type="avs:MessageControlType">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The indicator used to distinguish a live Message from a test Message.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="MessagingPartyWithoutCode">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a MessagingParty.</xs:documentation>
         <xs:documentation source="ddex:Comment">Explanatory Note: This Composite is named MessagingPartyWithoutCode to disambiguate it from the basic MessagingParty Composite.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="PartyId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An Identifier of a Party according to the DdexPartyId standard DDEX-DPID.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:pattern value="PADPIDA[a-zA-Z0-9]+"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:element name="PartyName" minOccurs="0" type="ern-c-ws:PartyNameWithoutCode">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the PartyNames for the Party handling the Message.</xs:documentation>
               <xs:documentation source="ddex:Comment">Further Reading: https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/guidance-on-contributors%2C-artists-and-writers/lengths-of-artist-names</xs:documentation>
               <xs:documentation source="ddex:Comment">Further Reading: https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/general-guidance-on-messages/field-length-and-precision</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="TradingName" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing a TradingName for the Party handling the Message.</xs:documentation>
               <xs:documentation source="ddex:Comment">Further Reading: https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/guidance-on-contributors%2C-artists-and-writers/lengths-of-artist-names</xs:documentation>
               <xs:documentation source="ddex:Comment">Further Reading: https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/general-guidance-on-messages/field-length-and-precision</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="MusicalWorkId">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a MusicalWorkId.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="ISWC" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The ISWC (International Standard Musical Work Code defined in ISO 15707) identifying the MusicalWork. An ISWC comprises three parts: the letter 'T', followed by nine digits and then one check digit. DDEX will enforce the syntax [a-zA-Z][0-9]{10} in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="OpusNumber" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The MusicalWorkId identifying the MusicalWork within the catalog of its Composer (typically of classical music) as an opus number.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ComposerCatalogNumber"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A MusicalWorkId identifying a MusicalWork within the catalog of its Composer (typically of classical music) according to a standardized numbering (e.g. 'K' numbers for Koechel's catalog of Mozart).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ProprietaryId"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:ProprietaryId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier of the MusicalWork.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="IsReplaced" type="xs:boolean">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The Flag indicating whether this Identifier is old and has been replaced by a new one (=true) or not (=false). The Flag may only be set to True when the new Identifier is also provided. If the Flag is not set, this Identifier is deemed to be the current one. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="Name">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a Name.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="LanguageAndScriptCode" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Language and script of the Name as defined in IETF RfC 5646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-script][-region][-variant]. A list of common language/script combinations has been published in the Language Metadata Table (LMT) at https://www.mesaonline.org/lmt by the Media &amp; Entertainment Services Alliance. Other language/script combinations allowed by IETF RfC 5646 are also valid. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="PartyDescriptor">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a Party. Parties are typically described through Names and/or Identifiers.</xs:documentation>
      </xs:annotation>
      <xs:choice>
         <xs:element name="PartyId"
                     maxOccurs="unbounded"
                     type="ern-c-ws:DetailedPartyId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the PartyId for the Party. If no Namespace is given, the Identifier is a DdexPartyId (DPID). Note that DPIDs are not normally used to identify Artists, producers or other Creators.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:sequence>
            <xs:element name="PartyName" maxOccurs="unbounded" type="ern-c-ws:PartyName">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of the PartyName(s).</xs:documentation>
                  <xs:documentation source="ddex:Comment">Further Reading: https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/guidance-on-contributors%2C-artists-and-writers/lengths-of-artist-names</xs:documentation>
                  <xs:documentation source="ddex:Comment">Further Reading: https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/general-guidance-on-messages/field-length-and-precision</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="PartyId"
                        minOccurs="0"
                        maxOccurs="unbounded"
                        type="ern-c-ws:DetailedPartyId">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of the PartyId for the Party. If no Namespace is given, the Identifier is a DdexPartyId (DPID). Note that DPIDs are not normally used to identify Artists, producers or other Creators.</xs:documentation>
               </xs:annotation>
            </xs:element>
         </xs:sequence>
      </xs:choice>
   </xs:complexType>
   <xs:complexType name="PartyName">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a PartyName. Name details for a Party typically either contain a FullName or a KeyName.</xs:documentation>
         <xs:documentation source="ddex:Comment">Further Reading: https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/guidance-on-contributors%2C-artists-and-writers/lengths-of-artist-names</xs:documentation>
         <xs:documentation source="ddex:Comment">Further Reading: https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/general-guidance-on-messages/field-length-and-precision</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="FullName" type="ern-c-ws:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing the complete Name of the Party, in its normal form of presentation (e.g. John H. Smith, Acme Music Inc, the Beatles).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="FullNameAsciiTranscribed" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The FullName transcribed using 7-bit ASCII code.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="FullNameIndexed" minOccurs="0" type="ern-c-ws:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing the complete Name of the Party in the form in which it normally appears in an alphabetic index, with the KeyName first (e.g. Smith, John H.; Beatles, The).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="NamesBeforeKeyName" minOccurs="0" type="ern-c-ws:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing the Name(s) preceding the KeyName in the FullName (and that is placed after it in a FullNameIndexed). Examples: 'George' in 'George Michael'; 'John Fitzgerald' in 'John Fitzgerald Kennedy'. Not all PartyNames have a NamesBeforeKeyName (e.g. Madonna, EMI Music Inc).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="KeyName" minOccurs="0" type="ern-c-ws:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing the Part of a Name of the Party normally used to index an entry in an alphabetical list, such as 'Smith' (in John Smith) or 'Garcia Marquez' or 'Madonna' or 'Francis de Sales' (in Saint Francis de Sales). For persons, this normally corresponds to the 'family name' or names, which in Western name forms usually comes as a surname at the end of a FullName, and in Asian name forms often at the beginning of a FullName. </xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="NamesAfterKeyName" minOccurs="0" type="ern-c-ws:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing the Name(s) following the KeyName. Example:'Ibrahim' (in Anwar Ibrahim). This is common, e.g., in many Asian personal name forms where a FullName begins with the KeyName, which is followed by other names.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="AbbreviatedName" minOccurs="0" type="ern-c-ws:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing a short version of the PartyName (e.g. for use on devices with a small display).</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="LanguageAndScriptCode" type="xs:string">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The Language and script for the Elements of the PartyName as defined in IETF RfC 5646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-script][-region][-variant]. A list of common language/script combinations has been published in the Language Metadata Table (LMT) at https://www.mesaonline.org/lmt by the Media &amp; Entertainment Services Alliance. Other language/script combinations allowed by IETF RfC 5646 are also valid. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="PartyNameWithoutCode">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a PartyName. Name details for a Party typically either contain a FullName or a KeyName.</xs:documentation>
         <xs:documentation source="ddex:Comment">Explanatory Note: This Composite is named PartyNameWithoutCode to disambiguate it from the basic PartyName Composite.</xs:documentation>
         <xs:documentation source="ddex:Comment">Further Reading: https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/guidance-on-contributors%2C-artists-and-writers/lengths-of-artist-names</xs:documentation>
         <xs:documentation source="ddex:Comment">Further Reading: https://kb.ddex.net/implementing-each-standard/best-practices-for-all-ddex-standards/general-guidance-on-messages/field-length-and-precision</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="FullName" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The complete Name of the Party, in its normal form of presentation (e.g. John H. Smith, Acme Music Inc, the Beatles).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="FullNameAsciiTranscribed" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The FullName transcribed using 7-bit ASCII code.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="FullNameIndexed" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The complete Name of the Party in the form in which it normally appears in an alphabetic index, with the KeyName first (e.g. Smith, John H.; Beatles, The).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="NamesBeforeKeyName" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The Name(s) preceding the KeyName in the FullName (and that is placed after it in a FullNameIndexed). Examples: 'George' in 'George Michael'; 'John Fitzgerald' in 'John Fitzgerald Kennedy'. Not all PartyNames have a NamesBeforeKeyName (e.g. Madonna, EMI Music Inc).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="KeyName" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The Part of a Name of the Party normally used to index an entry in an alphabetical list, such as 'Smith' (in John Smith) or 'Garcia Marquez' or 'Madonna' or 'Francis de Sales' (in Saint Francis de Sales). For persons, this normally corresponds to the 'family name' or names, which in Western name forms usually comes as a surname at the end of a FullName, and in Asian name forms often at the beginning of a FullName. </xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="NamesAfterKeyName" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The Name(s) following the KeyName. Example: 'Ibrahim' (in Anwar Ibrahim). This is common, e.g., in many Asian personal name forms where a FullName begins with the KeyName, which is followed by other names.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="AbbreviatedName" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A short version of the PartyName (e.g. for use on devices with a small display).</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="ProprietaryId">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="Namespace" type="xs:string" use="required">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Namespace of the ProprietaryIdentifier. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="SupplyChainStatus">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a SupplyChainStatus.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="avs:SupplyChainStatus">
            <xs:attribute name="Namespace" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Namespace of the SupplyChainStatus. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
            <xs:attribute name="UserDefinedValue" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A UserDefined value of the SupplyChainStatus. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="ReleaseId">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a ReleaseId. If available, a GRid should always to be used. If the Release is an abstraction of a complete PhysicalProduct (such as a CD Album), the ICPN of the PhysicalProduct may be used instead.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="GRid" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The GRid identifying the Release. This is the preferred Element and is mandatory if a GRid is available. A GRid comprises four parts: the xs:string 'A1', followed by five alphanumeric characters, ten alphanumeric characters and and one alphanumeric character. DDEX will enforce the syntax [a-zA-Z0-9]{18} in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ICPN" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An ICPN used as proxy for identification of the Release. If the Release is an abstraction of a PhysicalProduct, this may be the ICPN identifying the complete PhysicalProduct. An ICPN can be a UPC, EAN, JAN or any other bar code identifying, for example, the abstracted PhysicalProduct.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="CatalogNumber" minOccurs="0" type="ern-c-ws:CatalogNumber">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the CatalogNumber of the Release.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ProprietaryId"
                     minOccurs="0"
                     maxOccurs="unbounded"
                     type="ern-c-ws:ProprietaryId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier of the Release.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
</xs:schema>
