<?php

namespace DDEX\DSR\DSR_410;

/**
 * Class representing SalesToRecordCompanyByTerritoryType
 *
 * A ddex:Composite containing details of ddex:SalesTransactions reported by a ddex:DSP to a record company for a specific ddex:Territory.
 * XSD Type: SalesToRecordCompanyByTerritory
 */
class SalesToRecordCompanyByTerritoryType
{
    /**
     * The ddex:Language and script for the ddex:Elements of the SalesByTerritory as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. ddex:Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML ddex:Attribute.
     *
     * @var string $languageAndScriptCode
     */
    private $languageAndScriptCode = null;

    /**
     * A ddex:Territory for which ddex:SalesTransactions are reported (represented by an ISO 3166-1 iso3166a2:TerritoryCode).
     *
     * @var string[] $territoryCode
     */
    private $territoryCode = [
        
    ];

    /**
     * A ddex:Composite containing details of a ddex:TaxRate applicable to the total ddex:Amount to be paid. Within the DSR ddex:Message, only one of the two ddex:TaxRate ddex:Elements (here and in dsr:DetailedDeal) may be filled.
     *
     * @var \DDEX\ddexC\TaxRateType[] $taxRate
     */
    private $taxRate = [
        
    ];

    /**
     * A ddex:Composite containing details of the terms and conditions of the ddex:Deal under which sales were transacted. (Note: The ddex:Amount reported in this ddex:Composite is an estimate based on best knowledge on the side of the ddex:MessageSender with respect to the intellectual property rights controlled by the ddex:MessageRecipient. The default is that 100% ownership is assumed).
     *
     * @var \DDEX\DSR\DSR_410\DealForRecordCompaniesType $deal
     */
    private $deal = null;

    /**
     * A ddex:Composite containing details of the ddex:SalesTransactions for a ddex:Release, reported by the ddex:DSP to the record company.
     *
     * @var \DDEX\DSR\DSR_410\ReleaseTransactionsToRecordCompanyType[] $releaseTransactions
     */
    private $releaseTransactions = [
        
    ];

    /**
     * A ddex:Composite containing information to support the calculation of the record company's market share of all ddex:Releases provided by a ddex:DSP to ddex:Consumers for a specified ddex:UseType.
     *
     * @var \DDEX\ddexC\RecordCompanyMarketShareDataType[] $recordCompanyMarketShareData
     */
    private $recordCompanyMarketShareData = [
        
    ];

    /**
     * A ddex:Composite containing a ddex:NumberOfSubscribers for the ddex:UseType for the ddex:DSP (applicable only where a ddex:Subscription ddex:Service is employed).
     *
     * @var \DDEX\ddexC\NumberOfSubscribersType[] $numberOfSubscribers
     */
    private $numberOfSubscribers = [
        
    ];

    /**
     * A ddex:Composite containing details of the gross ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @var \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType[] $dspGrossRevenue
     */
    private $dspGrossRevenue = [
        
    ];

    /**
     * A ddex:Composite containing details of the net ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @var \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType[] $dspNetRevenue
     */
    private $dspNetRevenue = [
        
    ];

    /**
     * A ddex:Composite containing details of the ddex:Amount deducted by the ddex:DSP from gross ddex:Revenue, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @var \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType[] $dspDeductionsAmount
     */
    private $dspDeductionsAmount = [
        
    ];

    /**
     * A ddex:Composite containing details of the percentage which represents a share of a net ddex:Revenue generated by the ddex:DSP which is due to the record company, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @var \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType[] $percentageNetRevenueShare
     */
    private $percentageNetRevenueShare = [
        
    ];

    /**
     * The minimum ddex:Amount that has to be paid by each ddex:Customer to the ddex:DSP for a ddex:Subscription for the ddex:UseType.
     *
     * @var float $minimumAmountPerCustomer
     */
    private $minimumAmountPerCustomer = null;

    /**
     * The ddex:Amount representing the total wholesale revenue.
     *
     * @var float $wholesaleAmountTotal
     */
    private $wholesaleAmountTotal = null;

    /**
     * The ddex:Amount representing the total wholesale revenue reported in the ddex:CurrencyOfAccounting.
     *
     * @var float $wholesaleAmountTotalInCurrencyOfAccounting
     */
    private $wholesaleAmountTotalInCurrencyOfAccounting = null;

    /**
     * The calculated ddex:Total of ddex:AmountPayables in the ddex:CurrencyOfAccounting.
     *
     * @var float $totalAmountPayableInCurrencyOfAccounting
     */
    private $totalAmountPayableInCurrencyOfAccounting = null;

    /**
     * The conversion ddex:Rate applicable to the ddex:TotalAmountPayableInCurrencyOfAccounting.
     *
     * @var float $currencyExchangeRate
     */
    private $currencyExchangeRate = null;

    /**
     * A ddex:Composite containing details of a ddex:ConversionRate between the ddex:CurrencyOfAccounting and an alternative ddex:Currency.
     *
     * @var \DDEX\ddexC\ConversionRateType[] $alternativeConversionRate
     */
    private $alternativeConversionRate = [
        
    ];

    /**
     * Gets as languageAndScriptCode
     *
     * The ddex:Language and script for the ddex:Elements of the SalesByTerritory as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. ddex:Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML ddex:Attribute.
     *
     * @return string
     */
    public function getLanguageAndScriptCode()
    {
        return $this->languageAndScriptCode;
    }

    /**
     * Sets a new languageAndScriptCode
     *
     * The ddex:Language and script for the ddex:Elements of the SalesByTerritory as defined in IETF RfC 4646. The default is the same as indicated for the containing composite. ddex:Language and Script are provided as lang[-scipt][-region][-variant]. This is represented in an XML schema as an XML ddex:Attribute.
     *
     * @param string $languageAndScriptCode
     * @return self
     */
    public function setLanguageAndScriptCode($languageAndScriptCode)
    {
        $this->languageAndScriptCode = $languageAndScriptCode;
        return $this;
    }

    /**
     * Adds as territoryCode
     *
     * A ddex:Territory for which ddex:SalesTransactions are reported (represented by an ISO 3166-1 iso3166a2:TerritoryCode).
     *
     * @return self
     * @param string $territoryCode
     */
    public function addToTerritoryCode($territoryCode)
    {
        $this->territoryCode[] = $territoryCode;
        return $this;
    }

    /**
     * isset territoryCode
     *
     * A ddex:Territory for which ddex:SalesTransactions are reported (represented by an ISO 3166-1 iso3166a2:TerritoryCode).
     *
     * @param int|string $index
     * @return bool
     */
    public function issetTerritoryCode($index)
    {
        return isset($this->territoryCode[$index]);
    }

    /**
     * unset territoryCode
     *
     * A ddex:Territory for which ddex:SalesTransactions are reported (represented by an ISO 3166-1 iso3166a2:TerritoryCode).
     *
     * @param int|string $index
     * @return void
     */
    public function unsetTerritoryCode($index)
    {
        unset($this->territoryCode[$index]);
    }

    /**
     * Gets as territoryCode
     *
     * A ddex:Territory for which ddex:SalesTransactions are reported (represented by an ISO 3166-1 iso3166a2:TerritoryCode).
     *
     * @return string[]
     */
    public function getTerritoryCode()
    {
        return $this->territoryCode;
    }

    /**
     * Sets a new territoryCode
     *
     * A ddex:Territory for which ddex:SalesTransactions are reported (represented by an ISO 3166-1 iso3166a2:TerritoryCode).
     *
     * @param string $territoryCode
     * @return self
     */
    public function setTerritoryCode(array $territoryCode)
    {
        $this->territoryCode = $territoryCode;
        return $this;
    }

    /**
     * Adds as taxRate
     *
     * A ddex:Composite containing details of a ddex:TaxRate applicable to the total ddex:Amount to be paid. Within the DSR ddex:Message, only one of the two ddex:TaxRate ddex:Elements (here and in dsr:DetailedDeal) may be filled.
     *
     * @return self
     * @param \DDEX\ddexC\TaxRateType $taxRate
     */
    public function addToTaxRate(\DDEX\ddexC\TaxRateType $taxRate)
    {
        $this->taxRate[] = $taxRate;
        return $this;
    }

    /**
     * isset taxRate
     *
     * A ddex:Composite containing details of a ddex:TaxRate applicable to the total ddex:Amount to be paid. Within the DSR ddex:Message, only one of the two ddex:TaxRate ddex:Elements (here and in dsr:DetailedDeal) may be filled.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetTaxRate($index)
    {
        return isset($this->taxRate[$index]);
    }

    /**
     * unset taxRate
     *
     * A ddex:Composite containing details of a ddex:TaxRate applicable to the total ddex:Amount to be paid. Within the DSR ddex:Message, only one of the two ddex:TaxRate ddex:Elements (here and in dsr:DetailedDeal) may be filled.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetTaxRate($index)
    {
        unset($this->taxRate[$index]);
    }

    /**
     * Gets as taxRate
     *
     * A ddex:Composite containing details of a ddex:TaxRate applicable to the total ddex:Amount to be paid. Within the DSR ddex:Message, only one of the two ddex:TaxRate ddex:Elements (here and in dsr:DetailedDeal) may be filled.
     *
     * @return \DDEX\ddexC\TaxRateType[]
     */
    public function getTaxRate()
    {
        return $this->taxRate;
    }

    /**
     * Sets a new taxRate
     *
     * A ddex:Composite containing details of a ddex:TaxRate applicable to the total ddex:Amount to be paid. Within the DSR ddex:Message, only one of the two ddex:TaxRate ddex:Elements (here and in dsr:DetailedDeal) may be filled.
     *
     * @param \DDEX\ddexC\TaxRateType[] $taxRate
     * @return self
     */
    public function setTaxRate(array $taxRate = null)
    {
        $this->taxRate = $taxRate;
        return $this;
    }

    /**
     * Gets as deal
     *
     * A ddex:Composite containing details of the terms and conditions of the ddex:Deal under which sales were transacted. (Note: The ddex:Amount reported in this ddex:Composite is an estimate based on best knowledge on the side of the ddex:MessageSender with respect to the intellectual property rights controlled by the ddex:MessageRecipient. The default is that 100% ownership is assumed).
     *
     * @return \DDEX\DSR\DSR_410\DealForRecordCompaniesType
     */
    public function getDeal()
    {
        return $this->deal;
    }

    /**
     * Sets a new deal
     *
     * A ddex:Composite containing details of the terms and conditions of the ddex:Deal under which sales were transacted. (Note: The ddex:Amount reported in this ddex:Composite is an estimate based on best knowledge on the side of the ddex:MessageSender with respect to the intellectual property rights controlled by the ddex:MessageRecipient. The default is that 100% ownership is assumed).
     *
     * @param \DDEX\DSR\DSR_410\DealForRecordCompaniesType $deal
     * @return self
     */
    public function setDeal(?\DDEX\DSR\DSR_410\DealForRecordCompaniesType $deal = null)
    {
        $this->deal = $deal;
        return $this;
    }

    /**
     * Adds as releaseTransactions
     *
     * A ddex:Composite containing details of the ddex:SalesTransactions for a ddex:Release, reported by the ddex:DSP to the record company.
     *
     * @return self
     * @param \DDEX\DSR\DSR_410\ReleaseTransactionsToRecordCompanyType $releaseTransactions
     */
    public function addToReleaseTransactions(\DDEX\DSR\DSR_410\ReleaseTransactionsToRecordCompanyType $releaseTransactions)
    {
        $this->releaseTransactions[] = $releaseTransactions;
        return $this;
    }

    /**
     * isset releaseTransactions
     *
     * A ddex:Composite containing details of the ddex:SalesTransactions for a ddex:Release, reported by the ddex:DSP to the record company.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetReleaseTransactions($index)
    {
        return isset($this->releaseTransactions[$index]);
    }

    /**
     * unset releaseTransactions
     *
     * A ddex:Composite containing details of the ddex:SalesTransactions for a ddex:Release, reported by the ddex:DSP to the record company.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetReleaseTransactions($index)
    {
        unset($this->releaseTransactions[$index]);
    }

    /**
     * Gets as releaseTransactions
     *
     * A ddex:Composite containing details of the ddex:SalesTransactions for a ddex:Release, reported by the ddex:DSP to the record company.
     *
     * @return \DDEX\DSR\DSR_410\ReleaseTransactionsToRecordCompanyType[]
     */
    public function getReleaseTransactions()
    {
        return $this->releaseTransactions;
    }

    /**
     * Sets a new releaseTransactions
     *
     * A ddex:Composite containing details of the ddex:SalesTransactions for a ddex:Release, reported by the ddex:DSP to the record company.
     *
     * @param \DDEX\DSR\DSR_410\ReleaseTransactionsToRecordCompanyType[] $releaseTransactions
     * @return self
     */
    public function setReleaseTransactions(array $releaseTransactions)
    {
        $this->releaseTransactions = $releaseTransactions;
        return $this;
    }

    /**
     * Adds as recordCompanyMarketShareData
     *
     * A ddex:Composite containing information to support the calculation of the record company's market share of all ddex:Releases provided by a ddex:DSP to ddex:Consumers for a specified ddex:UseType.
     *
     * @return self
     * @param \DDEX\ddexC\RecordCompanyMarketShareDataType $recordCompanyMarketShareData
     */
    public function addToRecordCompanyMarketShareData(\DDEX\ddexC\RecordCompanyMarketShareDataType $recordCompanyMarketShareData)
    {
        $this->recordCompanyMarketShareData[] = $recordCompanyMarketShareData;
        return $this;
    }

    /**
     * isset recordCompanyMarketShareData
     *
     * A ddex:Composite containing information to support the calculation of the record company's market share of all ddex:Releases provided by a ddex:DSP to ddex:Consumers for a specified ddex:UseType.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetRecordCompanyMarketShareData($index)
    {
        return isset($this->recordCompanyMarketShareData[$index]);
    }

    /**
     * unset recordCompanyMarketShareData
     *
     * A ddex:Composite containing information to support the calculation of the record company's market share of all ddex:Releases provided by a ddex:DSP to ddex:Consumers for a specified ddex:UseType.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetRecordCompanyMarketShareData($index)
    {
        unset($this->recordCompanyMarketShareData[$index]);
    }

    /**
     * Gets as recordCompanyMarketShareData
     *
     * A ddex:Composite containing information to support the calculation of the record company's market share of all ddex:Releases provided by a ddex:DSP to ddex:Consumers for a specified ddex:UseType.
     *
     * @return \DDEX\ddexC\RecordCompanyMarketShareDataType[]
     */
    public function getRecordCompanyMarketShareData()
    {
        return $this->recordCompanyMarketShareData;
    }

    /**
     * Sets a new recordCompanyMarketShareData
     *
     * A ddex:Composite containing information to support the calculation of the record company's market share of all ddex:Releases provided by a ddex:DSP to ddex:Consumers for a specified ddex:UseType.
     *
     * @param \DDEX\ddexC\RecordCompanyMarketShareDataType[] $recordCompanyMarketShareData
     * @return self
     */
    public function setRecordCompanyMarketShareData(array $recordCompanyMarketShareData = null)
    {
        $this->recordCompanyMarketShareData = $recordCompanyMarketShareData;
        return $this;
    }

    /**
     * Adds as numberOfSubscribers
     *
     * A ddex:Composite containing a ddex:NumberOfSubscribers for the ddex:UseType for the ddex:DSP (applicable only where a ddex:Subscription ddex:Service is employed).
     *
     * @return self
     * @param \DDEX\ddexC\NumberOfSubscribersType $numberOfSubscribers
     */
    public function addToNumberOfSubscribers(\DDEX\ddexC\NumberOfSubscribersType $numberOfSubscribers)
    {
        $this->numberOfSubscribers[] = $numberOfSubscribers;
        return $this;
    }

    /**
     * isset numberOfSubscribers
     *
     * A ddex:Composite containing a ddex:NumberOfSubscribers for the ddex:UseType for the ddex:DSP (applicable only where a ddex:Subscription ddex:Service is employed).
     *
     * @param int|string $index
     * @return bool
     */
    public function issetNumberOfSubscribers($index)
    {
        return isset($this->numberOfSubscribers[$index]);
    }

    /**
     * unset numberOfSubscribers
     *
     * A ddex:Composite containing a ddex:NumberOfSubscribers for the ddex:UseType for the ddex:DSP (applicable only where a ddex:Subscription ddex:Service is employed).
     *
     * @param int|string $index
     * @return void
     */
    public function unsetNumberOfSubscribers($index)
    {
        unset($this->numberOfSubscribers[$index]);
    }

    /**
     * Gets as numberOfSubscribers
     *
     * A ddex:Composite containing a ddex:NumberOfSubscribers for the ddex:UseType for the ddex:DSP (applicable only where a ddex:Subscription ddex:Service is employed).
     *
     * @return \DDEX\ddexC\NumberOfSubscribersType[]
     */
    public function getNumberOfSubscribers()
    {
        return $this->numberOfSubscribers;
    }

    /**
     * Sets a new numberOfSubscribers
     *
     * A ddex:Composite containing a ddex:NumberOfSubscribers for the ddex:UseType for the ddex:DSP (applicable only where a ddex:Subscription ddex:Service is employed).
     *
     * @param \DDEX\ddexC\NumberOfSubscribersType[] $numberOfSubscribers
     * @return self
     */
    public function setNumberOfSubscribers(array $numberOfSubscribers = null)
    {
        $this->numberOfSubscribers = $numberOfSubscribers;
        return $this;
    }

    /**
     * Adds as dspGrossRevenue
     *
     * A ddex:Composite containing details of the gross ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @return self
     * @param \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspGrossRevenue
     */
    public function addToDspGrossRevenue(\DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspGrossRevenue)
    {
        $this->dspGrossRevenue[] = $dspGrossRevenue;
        return $this;
    }

    /**
     * isset dspGrossRevenue
     *
     * A ddex:Composite containing details of the gross ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetDspGrossRevenue($index)
    {
        return isset($this->dspGrossRevenue[$index]);
    }

    /**
     * unset dspGrossRevenue
     *
     * A ddex:Composite containing details of the gross ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetDspGrossRevenue($index)
    {
        unset($this->dspGrossRevenue[$index]);
    }

    /**
     * Gets as dspGrossRevenue
     *
     * A ddex:Composite containing details of the gross ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @return \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType[]
     */
    public function getDspGrossRevenue()
    {
        return $this->dspGrossRevenue;
    }

    /**
     * Sets a new dspGrossRevenue
     *
     * A ddex:Composite containing details of the gross ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType[] $dspGrossRevenue
     * @return self
     */
    public function setDspGrossRevenue(array $dspGrossRevenue = null)
    {
        $this->dspGrossRevenue = $dspGrossRevenue;
        return $this;
    }

    /**
     * Adds as dspNetRevenue
     *
     * A ddex:Composite containing details of the net ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @return self
     * @param \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspNetRevenue
     */
    public function addToDspNetRevenue(\DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspNetRevenue)
    {
        $this->dspNetRevenue[] = $dspNetRevenue;
        return $this;
    }

    /**
     * isset dspNetRevenue
     *
     * A ddex:Composite containing details of the net ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetDspNetRevenue($index)
    {
        return isset($this->dspNetRevenue[$index]);
    }

    /**
     * unset dspNetRevenue
     *
     * A ddex:Composite containing details of the net ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetDspNetRevenue($index)
    {
        unset($this->dspNetRevenue[$index]);
    }

    /**
     * Gets as dspNetRevenue
     *
     * A ddex:Composite containing details of the net ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @return \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType[]
     */
    public function getDspNetRevenue()
    {
        return $this->dspNetRevenue;
    }

    /**
     * Sets a new dspNetRevenue
     *
     * A ddex:Composite containing details of the net ddex:Revenue of the ddex:DSP for the ddex:Territory, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType[] $dspNetRevenue
     * @return self
     */
    public function setDspNetRevenue(array $dspNetRevenue = null)
    {
        $this->dspNetRevenue = $dspNetRevenue;
        return $this;
    }

    /**
     * Adds as dspDeductionsAmount
     *
     * A ddex:Composite containing details of the ddex:Amount deducted by the ddex:DSP from gross ddex:Revenue, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @return self
     * @param \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspDeductionsAmount
     */
    public function addToDspDeductionsAmount(\DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $dspDeductionsAmount)
    {
        $this->dspDeductionsAmount[] = $dspDeductionsAmount;
        return $this;
    }

    /**
     * isset dspDeductionsAmount
     *
     * A ddex:Composite containing details of the ddex:Amount deducted by the ddex:DSP from gross ddex:Revenue, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetDspDeductionsAmount($index)
    {
        return isset($this->dspDeductionsAmount[$index]);
    }

    /**
     * unset dspDeductionsAmount
     *
     * A ddex:Composite containing details of the ddex:Amount deducted by the ddex:DSP from gross ddex:Revenue, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetDspDeductionsAmount($index)
    {
        unset($this->dspDeductionsAmount[$index]);
    }

    /**
     * Gets as dspDeductionsAmount
     *
     * A ddex:Composite containing details of the ddex:Amount deducted by the ddex:DSP from gross ddex:Revenue, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @return \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType[]
     */
    public function getDspDeductionsAmount()
    {
        return $this->dspDeductionsAmount;
    }

    /**
     * Sets a new dspDeductionsAmount
     *
     * A ddex:Composite containing details of the ddex:Amount deducted by the ddex:DSP from gross ddex:Revenue, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType[] $dspDeductionsAmount
     * @return self
     */
    public function setDspDeductionsAmount(array $dspDeductionsAmount = null)
    {
        $this->dspDeductionsAmount = $dspDeductionsAmount;
        return $this;
    }

    /**
     * Adds as percentageNetRevenueShare
     *
     * A ddex:Composite containing details of the percentage which represents a share of a net ddex:Revenue generated by the ddex:DSP which is due to the record company, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @return self
     * @param \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $percentageNetRevenueShare
     */
    public function addToPercentageNetRevenueShare(\DDEX\ddexC\AmountByUseAndDistributionChannelTypeType $percentageNetRevenueShare)
    {
        $this->percentageNetRevenueShare[] = $percentageNetRevenueShare;
        return $this;
    }

    /**
     * isset percentageNetRevenueShare
     *
     * A ddex:Composite containing details of the percentage which represents a share of a net ddex:Revenue generated by the ddex:DSP which is due to the record company, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetPercentageNetRevenueShare($index)
    {
        return isset($this->percentageNetRevenueShare[$index]);
    }

    /**
     * unset percentageNetRevenueShare
     *
     * A ddex:Composite containing details of the percentage which represents a share of a net ddex:Revenue generated by the ddex:DSP which is due to the record company, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetPercentageNetRevenueShare($index)
    {
        unset($this->percentageNetRevenueShare[$index]);
    }

    /**
     * Gets as percentageNetRevenueShare
     *
     * A ddex:Composite containing details of the percentage which represents a share of a net ddex:Revenue generated by the ddex:DSP which is due to the record company, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @return \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType[]
     */
    public function getPercentageNetRevenueShare()
    {
        return $this->percentageNetRevenueShare;
    }

    /**
     * Sets a new percentageNetRevenueShare
     *
     * A ddex:Composite containing details of the percentage which represents a share of a net ddex:Revenue generated by the ddex:DSP which is due to the record company, specified for a ddex:UseType and a ddex:DistributionChannelType.
     *
     * @param \DDEX\ddexC\AmountByUseAndDistributionChannelTypeType[] $percentageNetRevenueShare
     * @return self
     */
    public function setPercentageNetRevenueShare(array $percentageNetRevenueShare = null)
    {
        $this->percentageNetRevenueShare = $percentageNetRevenueShare;
        return $this;
    }

    /**
     * Gets as minimumAmountPerCustomer
     *
     * The minimum ddex:Amount that has to be paid by each ddex:Customer to the ddex:DSP for a ddex:Subscription for the ddex:UseType.
     *
     * @return float
     */
    public function getMinimumAmountPerCustomer()
    {
        return $this->minimumAmountPerCustomer;
    }

    /**
     * Sets a new minimumAmountPerCustomer
     *
     * The minimum ddex:Amount that has to be paid by each ddex:Customer to the ddex:DSP for a ddex:Subscription for the ddex:UseType.
     *
     * @param float $minimumAmountPerCustomer
     * @return self
     */
    public function setMinimumAmountPerCustomer($minimumAmountPerCustomer)
    {
        $this->minimumAmountPerCustomer = $minimumAmountPerCustomer;
        return $this;
    }

    /**
     * Gets as wholesaleAmountTotal
     *
     * The ddex:Amount representing the total wholesale revenue.
     *
     * @return float
     */
    public function getWholesaleAmountTotal()
    {
        return $this->wholesaleAmountTotal;
    }

    /**
     * Sets a new wholesaleAmountTotal
     *
     * The ddex:Amount representing the total wholesale revenue.
     *
     * @param float $wholesaleAmountTotal
     * @return self
     */
    public function setWholesaleAmountTotal($wholesaleAmountTotal)
    {
        $this->wholesaleAmountTotal = $wholesaleAmountTotal;
        return $this;
    }

    /**
     * Gets as wholesaleAmountTotalInCurrencyOfAccounting
     *
     * The ddex:Amount representing the total wholesale revenue reported in the ddex:CurrencyOfAccounting.
     *
     * @return float
     */
    public function getWholesaleAmountTotalInCurrencyOfAccounting()
    {
        return $this->wholesaleAmountTotalInCurrencyOfAccounting;
    }

    /**
     * Sets a new wholesaleAmountTotalInCurrencyOfAccounting
     *
     * The ddex:Amount representing the total wholesale revenue reported in the ddex:CurrencyOfAccounting.
     *
     * @param float $wholesaleAmountTotalInCurrencyOfAccounting
     * @return self
     */
    public function setWholesaleAmountTotalInCurrencyOfAccounting($wholesaleAmountTotalInCurrencyOfAccounting)
    {
        $this->wholesaleAmountTotalInCurrencyOfAccounting = $wholesaleAmountTotalInCurrencyOfAccounting;
        return $this;
    }

    /**
     * Gets as totalAmountPayableInCurrencyOfAccounting
     *
     * The calculated ddex:Total of ddex:AmountPayables in the ddex:CurrencyOfAccounting.
     *
     * @return float
     */
    public function getTotalAmountPayableInCurrencyOfAccounting()
    {
        return $this->totalAmountPayableInCurrencyOfAccounting;
    }

    /**
     * Sets a new totalAmountPayableInCurrencyOfAccounting
     *
     * The calculated ddex:Total of ddex:AmountPayables in the ddex:CurrencyOfAccounting.
     *
     * @param float $totalAmountPayableInCurrencyOfAccounting
     * @return self
     */
    public function setTotalAmountPayableInCurrencyOfAccounting($totalAmountPayableInCurrencyOfAccounting)
    {
        $this->totalAmountPayableInCurrencyOfAccounting = $totalAmountPayableInCurrencyOfAccounting;
        return $this;
    }

    /**
     * Gets as currencyExchangeRate
     *
     * The conversion ddex:Rate applicable to the ddex:TotalAmountPayableInCurrencyOfAccounting.
     *
     * @return float
     */
    public function getCurrencyExchangeRate()
    {
        return $this->currencyExchangeRate;
    }

    /**
     * Sets a new currencyExchangeRate
     *
     * The conversion ddex:Rate applicable to the ddex:TotalAmountPayableInCurrencyOfAccounting.
     *
     * @param float $currencyExchangeRate
     * @return self
     */
    public function setCurrencyExchangeRate($currencyExchangeRate)
    {
        $this->currencyExchangeRate = $currencyExchangeRate;
        return $this;
    }

    /**
     * Adds as alternativeConversionRate
     *
     * A ddex:Composite containing details of a ddex:ConversionRate between the ddex:CurrencyOfAccounting and an alternative ddex:Currency.
     *
     * @return self
     * @param \DDEX\ddexC\ConversionRateType $alternativeConversionRate
     */
    public function addToAlternativeConversionRate(\DDEX\ddexC\ConversionRateType $alternativeConversionRate)
    {
        $this->alternativeConversionRate[] = $alternativeConversionRate;
        return $this;
    }

    /**
     * isset alternativeConversionRate
     *
     * A ddex:Composite containing details of a ddex:ConversionRate between the ddex:CurrencyOfAccounting and an alternative ddex:Currency.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetAlternativeConversionRate($index)
    {
        return isset($this->alternativeConversionRate[$index]);
    }

    /**
     * unset alternativeConversionRate
     *
     * A ddex:Composite containing details of a ddex:ConversionRate between the ddex:CurrencyOfAccounting and an alternative ddex:Currency.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetAlternativeConversionRate($index)
    {
        unset($this->alternativeConversionRate[$index]);
    }

    /**
     * Gets as alternativeConversionRate
     *
     * A ddex:Composite containing details of a ddex:ConversionRate between the ddex:CurrencyOfAccounting and an alternative ddex:Currency.
     *
     * @return \DDEX\ddexC\ConversionRateType[]
     */
    public function getAlternativeConversionRate()
    {
        return $this->alternativeConversionRate;
    }

    /**
     * Sets a new alternativeConversionRate
     *
     * A ddex:Composite containing details of a ddex:ConversionRate between the ddex:CurrencyOfAccounting and an alternative ddex:Currency.
     *
     * @param \DDEX\ddexC\ConversionRateType[] $alternativeConversionRate
     * @return self
     */
    public function setAlternativeConversionRate(array $alternativeConversionRate = null)
    {
        $this->alternativeConversionRate = $alternativeConversionRate;
        return $this;
    }
}

