<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:lraw="http://ddex.net/xml/lraw/11" xmlns:avs="http://ddex.net/xml/avs/avs"
   xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:xs="http://www.w3.org/2001/XMLSchema"
   targetNamespace="http://ddex.net/xml/lraw/11" elementFormDefault="unqualified"
   attributeFormDefault="unqualified">
   <xs:import namespace="http://ddex.net/xml/avs/avs"
      schemaLocation="http://ddex.net/xml/avs/avs-lraw.xsd"/>
   <xs:annotation>
      <xs:documentation>© 2006-2019 Digital Data Exchange, LLC (DDEX)</xs:documentation>
      <xs:documentation>This XML Schema Definition file is, together with all DDEX standards, subject to two licences: If you wish to evaluate whether the standard meets your needs please have a look at the Evaluation Licence at https://kb.ddex.net/display/HBK/Evaluation+Licence+for+DDEX+Standards. If you want to implement and use this DDEX standard, please take out an Implementation Licence. For details please go to http://ddex.net/apply-ddex-implementation-licence.</xs:documentation>
   </xs:annotation>
   <xs:element name="LinkResourceAndWorkMessage">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Message in the LRAW Standard, containing details of a link between a Resource eligible to be allocated an ISRC (i.e. a SoundRecording or a (short form) Video) and the MusicalWork(s) it uses.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element name="MessageHeader" type="lraw:MessageHeader">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The MessageHeader for the LinkResourceAndWorkMessage.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="PartyList" type="lraw:PartyList">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of one or more Parties relating to the reported MusicalWorks.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="AssertedLink" maxOccurs="unbounded" type="lraw:AssertedLink">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of the link between a SoundRecording and one or more MusicalWorks that it uses.</xs:documentation>
               </xs:annotation>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="LinkAcknowledgementMessage">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Message in the LRAW Standard that is sent to acknowledge a LinkResourceAndWorkMessage.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element name="MessageHeader" type="lraw:MessageHeader">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The MessageHeader for the LinkAcknowledgementMessage.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="LinkId" maxOccurs="unbounded" type="lraw:LinkId">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of Identifiers of the link that is acknowledged.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="Status" type="lraw:Status">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Status that is acknowledged.</xs:documentation>
               </xs:annotation>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:element name="LinkRequestMessage">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Message in the LRAW Standard that is sent to request a LinkResourceAndWorkMessage.</xs:documentation>
      </xs:annotation>
      <xs:complexType>
         <xs:sequence>
            <xs:element name="MessageHeader" type="lraw:MessageHeader">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The MessageHeader for the LinkRequestMessage.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="PartyList" type="lraw:PartyList">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of one or more Parties relating to the requested links.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="LinkRequest" maxOccurs="unbounded" type="lraw:LinkRequest">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A link that is requested.</xs:documentation>
               </xs:annotation>
            </xs:element>
         </xs:sequence>
      </xs:complexType>
   </xs:element>
   <xs:complexType name="Artist">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of an Artist. An Artist may be described through Name, Identifier and Roles.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="lraw:ddex_LocalPartyAnchorReference">
            <xs:attribute name="SequenceNumber" type="xs:integer">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The number indicating the order of the Artist in a group of Artists. This is represented in an XML schema as an XML Attribute. </xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="AssertedLink">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a link between a SoundRecording and one or more MusicalWorks that it uses.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="LinkId" type="lraw:LinkId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of Identifiers of the link.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="LinkRequestId" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An Identifier of a link request relating to the asserted link.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="Assertion" maxOccurs="unbounded" type="lraw:Assertion">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of an assertion about the link between the SoundRecording and one or more MusicalWorks that it uses.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ResourceWorkRelationshipType" minOccurs="0"
            type="avs:ResourceWorkRelationshipType">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Type of the relationship between the Resource and the work(s). If the Resource is a MultipleWorkResource (e.g. it contains samples, it is a medley or an interpellation), more than one MusicalWork may be specified.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:choice minOccurs="0">
            <xs:element name="SoundRecording" type="lraw:SoundRecording">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of the SoundRecording for which the link to the MusicalWorks is asserted.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="Video" type="lraw:Video">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of the Video for which the link to the MusicalWorks is asserted.</xs:documentation>
               </xs:annotation>
            </xs:element>
         </xs:choice>
         <xs:element name="MusicalWork" minOccurs="0" maxOccurs="unbounded" type="lraw:MusicalWork">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a MusicalWork used by the SoundRecording.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Asserter">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of an Asserter.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="lraw:ddex_LocalPartyAnchorReference">
            <xs:attribute name="AsserterType" type="avs:AsserterType" use="required">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The type of the Asserter.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="Assertion">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of an Assertion.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="Asserter" type="lraw:Asserter">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Reference for a Party (specific to this Message) asserting the link between a sound recording and the work(s) it uses. This is a LocalPartyAnchorReference starting with the letter P.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:choice minOccurs="0">
            <xs:element name="IsTrue" type="xs:boolean">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Flag indicating whether the Assertion is positive (=true) or not (=false).</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="MissingLinkReason" type="lraw:MissingLinkReason">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">An element that allows the sender to indicate why they do not have a link.</xs:documentation>
               </xs:annotation>
            </xs:element>
         </xs:choice>
         <xs:element name="AssertionDateTime" type="xs:dateTime">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The DateTime of the Assertion, in ISO 8601 format: YYYY-MM-DDThh:mm:ssTZD.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="LinkId">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of Identifiers of a link.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="ISLI" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The ISLI (International Standard Link Identifier as defined in ISO 17316) for the link.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ProprietaryId" minOccurs="0" maxOccurs="unbounded"
            type="lraw:ProprietaryId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier of the link.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="LinkRequest">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a request for a link.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="LinkRequestId" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An Identifier of the link request.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:choice>
            <xs:element name="SoundRecording" type="lraw:SoundRecording">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of the SoundRecording for which a link to a MusicalWork is requested.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="Video" type="lraw:Video">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of the Video for which a link to a MusicalWork is requested.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:element name="MusicalWork" type="lraw:MusicalWork">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of the MusicalWork for which a link to a Resource is requested.</xs:documentation>
               </xs:annotation>
            </xs:element>
         </xs:choice>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="MessageAuditTrail">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing information about Parties in between the original MessageSender and ultimate MessageRecipient.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="MessageAuditTrailEvent" maxOccurs="unbounded"
            type="lraw:MessageAuditTrailEvent">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a Party handling the Message and the Time at which the handling took place.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="LanguageAndScriptCode" type="xs:string">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The Language and script for the Elements of the MessageAuditTrail as defined in IETF RfC 5646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-script][-region][-variant]. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="MessageAuditTrailEvent">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a Party handling a Message and the Time at which the handling took place.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="MessagingPartyDescriptor" type="lraw:MessagingParty">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a MessagingParty.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="DateTime" type="xs:dateTime">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The DateTime at which the Message was handled by the MessagingParty (the only allowed format is ISO 8601:2004: YYYY-MM-DDThh:mm:ssTZD).</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="MessageHeader">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite placed at the beginning of each DdexMessage providing information about the Message, such as MessageSender, MessageRecipient and a Message creation time stamp.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="MessageThreadId" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A xs:string used to uniquely identify the thread of Messages of which the current Message is a part. The MessageThreadId shall be, in combination with the DdexPartyId (DPID) of the MessageSender, globally unique. Thus, a MessageSender shall never re-use a MessageThreadId. One example of such a 'thread' is the chain of NewReleaseMessages being sent from ReleaseCreator to wholesale ReleaseDistributor 1 to retail DSP when communicating information about the same Release(s). A common MessageThreadId will allow all these messages to be tied together.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageId" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A xs:string used to uniquely identify the current Message. The MessageId shall be, in combination with the DdexPartyId (DPID) of the MessageSender, globally unique. Thus, a MessageSender shall never re-use a MessageId.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageFileName" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The FileName, possibly including the FilePath, of the XML File containing the current Message.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageSender" type="lraw:MessagingParty">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the MessageSender.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="SentOnBehalfOf" minOccurs="0" type="lraw:MessagingParty">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the Party on whose behalf the Message is sent.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageRecipient" maxOccurs="unbounded" type="lraw:MessagingParty">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the MessageRecipient. Note that if multiple MessageRecipients are provided, all of them will be able to read this information.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageCreatedDateTime" type="xs:dateTime">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The DateTime on which the Message was created (the only allowed format is ISO 8601:2004: YYYY-MM-DDThh:mm:ssTZD).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageAuditTrail" minOccurs="0" type="lraw:MessageAuditTrail">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing information about Parties in between the original MessageSender and ultimate MessageRecipient.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="MessageControlType" minOccurs="0" type="avs:MessageControlType">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The indicator used to distinguish a live Message from a test Message.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="LanguageAndScriptCode" type="xs:string">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The Language and script for the Elements of the MessageHeader as defined in IETF RfC 5646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-script][-region][-variant]. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="MusicalWork">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a MusicalWork.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="MusicalWorkId" maxOccurs="unbounded" type="lraw:MusicalWorkId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a MusicalWorkId of the MusicalWork.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ReferenceTitleText" maxOccurs="unbounded" type="lraw:ReferenceTitleText">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the Title of the MusicalWork.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ReferenceTitle" minOccurs="0" maxOccurs="unbounded"
            type="lraw:ReferenceTitle">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a structured Title of the MusicalWork.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="Writer" minOccurs="0" type="lraw:MusicalWorkContributor">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a MusicalWorkContributor to the MusicalWork.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="MusicalWorkContributor">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details a MusicalWorkContributor.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="MusicalWorkContributorReference">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Reference for a MusicalWorkContributor (specific to this Message). This is a LocalPartyAnchorReference starting with the letter P.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:IDREF">
                  <xs:pattern value="P[\d\-_a-zA-Z]+"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:element name="MusicalWorkContributorRole" minOccurs="0" maxOccurs="unbounded"
            type="lraw:MusicalWorkContributorRole">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a role played by the Contributor in relation to the MusicalWork. Note: This can be used in a DdexMessage in relation to any Work, Performance or Fixation any of which may form the whole or part of the Resource itself. Example: if an 'AssociatedPerformer' is shown as a Contributor to a MusicalWork it refers to a performer of a Resource (e.g. a SoundRecording) expressing the MusicalWork.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Party">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a Party.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="PartyReference">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The Identifier (specific to the Message) of the Party. This is a LocalPartyAnchor starting with the letter P.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:ID">
                  <xs:pattern value="P[\d\-_a-zA-Z]+"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:choice>
            <xs:element name="PartyId" maxOccurs="unbounded" type="lraw:DetailedPartyId">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A Composite containing details of the PartyId for the Party. If no Namespace is given, the Identifier is a DdexPartyId (DPID). Note that DPIDs are not normally used to identify Artists, producers or other Creators.</xs:documentation>
               </xs:annotation>
            </xs:element>
            <xs:sequence>
               <xs:element name="PartyName" maxOccurs="unbounded" type="lraw:PartyName">
                  <xs:annotation>
                     <xs:documentation source="ddex:Definition">A Composite containing details of the PartyName(s).</xs:documentation>
                  </xs:annotation>
               </xs:element>
               <xs:element name="PartyId" minOccurs="0" maxOccurs="unbounded"
                  type="lraw:DetailedPartyId">
                  <xs:annotation>
                     <xs:documentation source="ddex:Definition">A Composite containing details of the PartyId for the Party. If no Namespace is given, the Identifier is a DdexPartyId (DPID). Note that DPIDs are not normally used to identify Artists, producers or other Creators.</xs:documentation>
                  </xs:annotation>
               </xs:element>
            </xs:sequence>
         </xs:choice>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="PartyList">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of one or more Parties.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="Party" maxOccurs="unbounded" type="lraw:Party">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a Party.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="ReferenceTitleText">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a Title.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="LanguageAndScriptCode" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Language and script for the Elements of the Title as defined in IETF RfC 5646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-script][-region][-variant]. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="SoundRecording">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a SoundRecording.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="ResourceId" maxOccurs="unbounded" type="lraw:SoundRecordingId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of SoundRecordingIds.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ReferenceTitleText" maxOccurs="unbounded" type="lraw:ReferenceTitleText">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the Title of the SoundRecording.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ReferenceTitle" minOccurs="0" maxOccurs="unbounded"
            type="lraw:ReferenceTitle">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a structured Title of the SoundRecording.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="DisplayArtistName" minOccurs="0" type="lraw:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing the Name to be used by a DSP when presenting Artist details of the Resource to a Consumer. A Resource-level DisplayArtistName shall only be provided if it differs from the DisplayArtistName for a Release that contains the Resource and is communicated in the same XML message.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="DisplayArtist" minOccurs="0" maxOccurs="unbounded" type="lraw:Artist">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the DisplayArtist for the SoundRecording. The DisplayArtist may be described through Name, Identifier and Roles.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="Duration" minOccurs="0" type="xs:duration">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The Duration of the SoundRecording (using the ISO 8601:2004 PT[[hhH]mmM]ssS format, where lower case characters indicate variables, upper case characters are part of the xs:string, e.g. one hour, two minutes and three seconds would be PT1H2M3S). The seconds section ss may include fractions (e.g. one minute and 30.5 seconds would be PT1M30.5S).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="PLineYear" minOccurs="0" type="xs:integer">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The Year of the PLine.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="Status">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a Status.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="avs:LinkAcknowledgementStatus">
            <xs:attribute name="Namespace" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Namespace of the detailed Status. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
            <xs:attribute name="UserDefinedValue" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A user-defined detailed Status that is acknowledged. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="Video">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a Video.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="ResourceId" maxOccurs="unbounded" type="lraw:VideoId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of VideoIds.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ReferenceTitleText" maxOccurs="unbounded" type="lraw:ReferenceTitleText">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the Title of the SoundRecording.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ReferenceTitle" minOccurs="0" maxOccurs="unbounded"
            type="lraw:ReferenceTitle">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a structured Title of the SoundRecording.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="DisplayArtistName" minOccurs="0" type="lraw:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing the Name to be used by a DSP when presenting Artist details of the Resource to a Consumer. A Resource-level DisplayArtistName shall only be provided if it differs from the DisplayArtistName for a Release that contains the Resource and is communicated in the same XML message.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="DisplayArtist" minOccurs="0" maxOccurs="unbounded" type="lraw:Artist">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the DisplayArtist for the SoundRecording. The DisplayArtist may be described through Name, Identifier and Roles.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="Duration" minOccurs="0" type="xs:duration">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The Duration of the SoundRecording (using the ISO 8601:2004 PT[[hhH]mmM]ssS format, where lower case characters indicate variables, upper case characters are part of the xs:string, e.g. one hour, two minutes and three seconds would be PT1H2M3S). The seconds section ss may include fractions (e.g. one minute and 30.5 seconds would be PT1M30.5S).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="PLineYear" minOccurs="0" type="xs:integer">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The Year of the PLine.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="CatalogNumber">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a CatalogNumber.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="Namespace" type="xs:string" use="required">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Namespace of the CatalogNumber. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="DetailedPartyId">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a PartyId.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="ISNI" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An International Standard Name Identifier, the ISO 27729 Standard Identifier for names. DDEX will enforce the syntax [0-9]{15}[X0-9] using XML Schema in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="DPID" minOccurs="0">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An Identifier of a Party according to the DdexPartyId standard DDEX-DPID.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:pattern value="PADPIDA[a-zA-Z0-9]+"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:element name="IpiNameNumber" minOccurs="0">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An Interested Party Identifier, a CISAC standard Identifier. An IpiNameNumber comprises 11 digits.</xs:documentation>
            </xs:annotation>
            <xs:simpleType>
               <xs:restriction base="xs:string">
                  <xs:pattern value="[0-9]{11}"/>
               </xs:restriction>
            </xs:simpleType>
         </xs:element>
         <xs:element name="IPN" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An International Performer Number, an IPDA Identifier.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="CisacSocietyId" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A CISAC Society Identifier, a CISAC standard Identifier for music rights societies.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ProprietaryId" minOccurs="0" maxOccurs="unbounded"
            type="lraw:ProprietaryId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier of the Party.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
   </xs:complexType>
   <xs:complexType name="MessagingParty">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a MessagingParty.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="PartyId" maxOccurs="unbounded" type="lraw:PartyId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the PartyId for the Party handling the Message. If no Namespace is given, the Identifier is a DdexPartyId (DPID). Note that DPIDs are not normally used to identify Artists, producers or other Creators.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="PartyName" minOccurs="0" type="lraw:PartyName">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the PartyNames for the Party handling the Message.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="TradingName" minOccurs="0" type="lraw:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing a TradingName for the Party handling the Message.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="LanguageAndScriptCode" type="xs:string">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The Language and script for the Elements of the MessagingParty as defined in IETF RfC 5646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-script][-region][-variant]. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="MissingLinkReason">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a MissingLinkReason.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="avs:MissingLinkReason">
            <xs:attribute name="Namespace" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Namespace of the MissingLinkReason. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
            <xs:attribute name="UserDefinedValue" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A UserDefined value of the MissingLinkReason. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="MusicalWorkContributorRole">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a MusicalWorkContributorRole. Note: This can be used in a DdexMessage in relation to any Work, Performance or Fixation any of which may form the whole or part of the Resource itself. Example: if an 'AssociatedPerformer' is shown as a Contributor to a MusicalWork it refers to a performer of a Resource (e.g. a SoundRecording) expressing the MusicalWork.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="avs:MusicalWorkContributorRole">
            <xs:attribute name="Namespace" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Namespace of the MusicalWorkContributorRole. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
            <xs:attribute name="UserDefinedValue" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">A UserDefined value of the MusicalWorkContributorRole. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="MusicalWorkId">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a MusicalWorkId.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="ISWC" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The ISWC (International Standard Musical Work Code defined in ISO 15707) identifying the MusicalWork. An ISWC comprises three parts: the letter 'T', followed by nine digits and then one check digit. DDEX will enforce the syntax [a-zA-Z][0-9]{10} using XML Schema in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="OpusNumber" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The MusicalWorkId identifying the MusicalWork within the catalog of its Composer (typically of classical music) as an opus number.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ComposerCatalogNumber" minOccurs="0" maxOccurs="unbounded"
            type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A MusicalWorkId identifying a MusicalWork within the catalog of its Composer (typically of classical music) according to a standardized numbering (e.g. 'K' numbers for Koechel's catalog of Mozart).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ProprietaryId" minOccurs="0" maxOccurs="unbounded"
            type="lraw:ProprietaryId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier of the MusicalWork.</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="IsReplaced" type="xs:boolean">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The Flag indicating whether this Identifier is old and has been replaced by a new one (=true) or not (=false). The Flag may only be set to True when the new Identifier is also provided. If the Flag is not set, this Identifier is deemed to be the current one.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="Name">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a Name.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="LanguageAndScriptCode" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Language and script of the Name as defined in IETF RfC 5646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-script][-region][-variant]. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="PartyId">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a PartyId. If no Namespace is given, the Identifier is a DdexPartyId (DPID). Note that DPIDs are not normally used to identify Artists, producers or other Creators.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="Namespace" type="xs:string">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Namespace of the PartyId if it belongs to a proprietary Party xs:ID scheme. If the PartyId is a DPID, the Namespace Element must not be used. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
            <xs:attribute name="IsDPID" type="xs:boolean">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Flag indicating whether the PartyId is a DPID (=true) or not (=false). This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
            <xs:attribute name="IsISNI" type="xs:boolean">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Flag indicating whether the PartyId is an ISNI (=true) or not (=false). This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="PartyName">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a PartyName. Name details for a Party typically either contain a FullName or a KeyName.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="FullName" type="lraw:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing the complete Name of the Party, in its normal form of presentation (e.g. John H. Smith, Acme Music Inc, the Beatles).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="FullNameAsciiTranscribed" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The FullName transcribed using 7-bit ASCII code.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="FullNameIndexed" minOccurs="0" type="lraw:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing the complete Name of the Party in the form in which it normally appears in an alphabetic index, with the KeyName first (e.g. Smith, John H.; Beatles, The).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="NamesBeforeKeyName" minOccurs="0" type="lraw:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing the Name(s) preceding the KeyName in the FullName (and that is placed after it in a FullNameIndexed). Examples: 'George' in 'George Michael'; 'John Fitzgerald' in 'John Fitzgerald Kennedy'. Not all PartyNames have a NamesBeforeKeyName (e.g. Madonna, EMI Music Inc).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="KeyName" minOccurs="0" type="lraw:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing the Part of a Name of the Party normally used to index an entry in an alphabetical list, such as 'Smith' (in John Smith) or 'Garcia Marquez' or 'Madonna' or 'Francis de Sales' (in Saint Francis de Sales). For persons, this normally corresponds to the 'family name' or names, which in Western name forms usually comes as a surname at the end of a FullName, and in Asian name forms often at the beginning of a FullName. </xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="NamesAfterKeyName" minOccurs="0" type="lraw:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing the Name(s) following the KeyName. Example:'Ibrahim' (in Anwar Ibrahim). This is common, e.g., in many Asian personal name forms where a FullName begins with the KeyName, which is followed by other names.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="AbbreviatedName" minOccurs="0" type="lraw:Name">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing a short version of the PartyName (e.g. for use on devices with a small display).</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="LanguageAndScriptCode" type="xs:string">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The Language and script for the Elements of the PartyName as defined in IETF RfC 5646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-script][-region][-variant]. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="ProprietaryId">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier.</xs:documentation>
      </xs:annotation>
      <xs:simpleContent>
         <xs:extension base="xs:string">
            <xs:attribute name="Namespace" type="xs:string" use="required">
               <xs:annotation>
                  <xs:documentation source="ddex:Definition">The Namespace of the ProprietaryIdentifier. This is represented in an XML schema as an XML Attribute.</xs:documentation>
               </xs:annotation>
            </xs:attribute>
         </xs:extension>
      </xs:simpleContent>
   </xs:complexType>
   <xs:complexType name="ReferenceTitle">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of a ReferenceTitle.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="TitleText" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The text of the ReferenceTitle.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="SubTitle" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A SubTitle of the ReferenceTitle, including Titles of Versions used to differentiate different versions of the same Title, as required by the GRid and ISRC ReferenceDescriptiveMetadataSets (where the SubTitle is called Version Title).</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="LanguageAndScriptCode" type="xs:string">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The Language and script for the Elements of the ReferenceTitle as defined in IETF RfC 5646. The default is the same as indicated for the containing composite. Language and Script are provided as lang[-script][-region][-variant]. This is represented in an XML schema as an XML Attribute.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="SoundRecordingId">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of SoundRecordingIds.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="ISRC" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The ISRC (International Standard Recording Code as defined in ISO 3901) for the SoundRecording. An ISRC comprises four parts: two characters, followed by three alphanumeric characters, then two digits and five digits. DDEX will enforce the syntax [a-zA-Z]{2}[a-zA-Z0-9]{3}[0-9]{7} using XML Schema in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="CatalogNumber" minOccurs="0" type="lraw:CatalogNumber">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the CatalogNumber of the SoundRecording.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ProprietaryId" minOccurs="0" maxOccurs="unbounded"
            type="lraw:ProprietaryId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier of the SoundRecording (usually one per society involved in the messaging).</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="IsReplaced" type="xs:boolean">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The Flag indicating whether this Identifier is old and has been replaced by a new one (=true) or not (=false). The Flag may only be set to True when the new Identifier is also provided. If the Flag is not set, this Identifier is deemed to be the current one.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:complexType name="VideoId">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A Composite containing details of Identifiers of a Video.</xs:documentation>
      </xs:annotation>
      <xs:sequence>
         <xs:element name="ISRC" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The ISRC (International Standard Recording Code as defined in ISO 3901) for the Video. An ISRC comprises four parts: two characters, followed by three alphanumeric characters, then two digits and five digits. DDEX will enforce the syntax [a-zA-Z]{2}[a-zA-Z0-9]{3}[0-9]{7} using XML Schema in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ISAN" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The ISAN (International Standard Audiovisual Number as defined in ISO 15706) for the Video. An ISAN comprises four blocks of four hexadecimal charaters followed by a check character. DDEX will enforce the syntax [A-F0-9]{12} using XML Schema in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="VISAN" minOccurs="0" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">The V-ISAN (Version Identifier of a International Standard Audiovisual Number as defined in ISO 15706-2) for the Video. A V-ISAN comprises four blocks of four hexadecimal charaters followed by a check character, followed by two further blocks of four hexadecimal characters, followed by a further check character. DDEX will enforce the syntax [A-F0-9]{24} using XML Schema in the future.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="CatalogNumber" minOccurs="0" type="lraw:CatalogNumber">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of the CatalogNumber of the Video.</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="ProprietaryId" minOccurs="0" maxOccurs="unbounded"
            type="lraw:ProprietaryId">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">A Composite containing details of a ProprietaryIdentifier of the Video (usually one per society involved in the messaging).</xs:documentation>
            </xs:annotation>
         </xs:element>
         <xs:element name="EIDR" minOccurs="0" maxOccurs="unbounded" type="xs:string">
            <xs:annotation>
               <xs:documentation source="ddex:Definition">An Identifier of the Video assigned by the Entertainment Identifier Registry Association (EIDR).</xs:documentation>
            </xs:annotation>
         </xs:element>
      </xs:sequence>
      <xs:attribute name="IsReplaced" type="xs:boolean">
         <xs:annotation>
            <xs:documentation source="ddex:Definition">The Flag indicating whether this Identifier is old and has been replaced by a new one (=true) or not (=false). The Flag may only be set to True when the new Identifier is also provided. If the Flag is not set, this Identifier is deemed to be the current one.</xs:documentation>
         </xs:annotation>
      </xs:attribute>
   </xs:complexType>
   <xs:simpleType name="ddex_LocalPartyAnchorReference">
      <xs:annotation>
         <xs:documentation source="ddex:Definition">A LocalAnchorReference which acts as a reference to a local Identifier of a Party. This LocalAnchorReference is a xs:string starting with the letter P.</xs:documentation>
      </xs:annotation>
      <xs:restriction base="xs:IDREF">
         <xs:pattern value="P[\d\-_a-zA-Z]+"/>
      </xs:restriction>
   </xs:simpleType>
</xs:schema>
